### ISSUE TITLE
when You drag a interfacce, it will out of control and won't react immediately

### ISSUE THREAD

**Issue by marcocrxu** [Eugeny/terminus#1489] opened 2019-09-10 04:48 UTC
Version: 1.0.90
Platform: win32 10.0.18362
Plugins: none

**Comment by lpreiner** [comment] 2019-09-11 18:52
I also have this behavior, but only with "Acrylic background" on and the "Background type" setting set to "Fluent."  Changing the type to Blur results in the window responding as I'd expect during dragging.  This has been an issue for several recent versions, but unfortunately, I can't pinpoint when it began.  I'm using a USB mouse.

Version: 1.0.91
Platform: win32 10.0.18362
Plugins: none

**Comment by sippeangelo** [comment] 2019-10-02 13:28
I'm having the same problem on a fresh install.

**Comment by Eugeny** [comment] 2019-11-25 10:33
Duplicate of #1130

**Closed by Eugeny** 2019-11-25 10:33 UTC
