### ISSUE TITLE
Not able to open a new terminal and rest is working

### ISSUE THREAD

**Issue by N0r1h** [Eugeny/terminus#1757] opened 2019-11-11 06:17 UTC
Version: 1.0.93-nightly.0
Platform: win32 10.0.18362
Plugins: none

I have opened the dev tools in setting and getting these error message in the console tab.

C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'LM' of undefined
TypeError: Cannot read property 'LM' of undefined
    at PowerShellCoreShellProvider.eval (webpack-internal:///192:4018:88)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///192:68:71)
    at new ZoneAwarePromise (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910:29)
    at __awaiter (webpack-internal:///192:64:12)
    at PowerShellCoreShellProvider.provide (webpack-internal:///192:4014:16)
    at eval (webpack-internal:///192:2595:110)
    at Array.map (<anonymous>)
    at TerminalService.eval (webpack-internal:///192:2595:99)
    at Generator.next (<anonymous>)
    at resolvePromise (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:831:31)
    at C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:741:17
    at rejected (webpack-internal:///192:66:89)
    at ZoneDelegate.invoke (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:391:26)
    at Object.onInvoke (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17343:37)
    at ZoneDelegate.invoke (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:390:52)
    at Zone.run (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:150:43)
    at C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:889:34
    at ZoneDelegate.invokeTask (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423:31)
    at Object.onInvokeTask (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334:37)
defaultErrorLogger @ C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getRegistryKey' of undefined
TypeError: Cannot read property 'getRegistryKey' of undefined
    at ShellIntegrationService.eval (webpack-internal:///370:6623:30)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///370:68:71)
    at new ZoneAwarePromise (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910:29)
    at __awaiter (webpack-internal:///370:64:12)
    at ShellIntegrationService.isInstalled (webpack-internal:///370:6618:16)
    at ShellIntegrationService.eval (webpack-internal:///370:6664:32)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///370:68:71)
    at new ZoneAwarePromise (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910:29)
    at resolvePromise (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:831:31)
    at C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:741:17
    at rejected (webpack-internal:///370:66:89)
    at ZoneDelegate.invoke (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:391:26)
    at Object.onInvoke (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17343:37)
    at ZoneDelegate.invoke (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:390:52)
    at Zone.run (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:150:43)
    at C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:889:34
    at ZoneDelegate.invokeTask (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423:31)
    at Object.onInvokeTask (C:\Users\Gyani\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334:37)

**Comment by Eugeny** [comment] 2019-11-11 11:00
Duplicate of #1727

**Closed by Eugeny** 2019-11-11 11:00 UTC
