### ISSUE TITLE
Terminus asking for private key passphrase though it isn't selected

### ISSUE THREAD

**Issue by Proxymiity** [Eugeny/terminus#3102] opened 2020-10-23 21:51 UTC
When I log to a ssh server, Terminus keeps asking me to enter my `$home/.ssh/id_rsa` passphrase even though I didn't select a private key to be used, but a password.
This renders the app unusable as I can't even login to servers using a normal 'password' auth.

Host config:
![image](https://i.iya.at/Terminus_dkLAHj.png)

Term output:
![image](https://i.iya.at/Terminus_7u8BS0.png)

**Comment by DeviantUK** [comment] 2020-12-04 15:32
I can confirm this problem.

**Comment by Eugeny** [comment] 2020-12-06 16:42
Duplicate of #2968

**Closed by Eugeny** 2020-12-06 16:42 UTC

**Comment by rbukovansky** [comment] 2020-12-07 18:50
Problem solved with the latest AppVeyor build! 🍾
