### ISSUE TITLE
Dependency fail n 18.04 Bionic - python-gnomekeyring

### ISSUE THREAD

**Issue by rufusshrestha** [Eugeny/terminus#343] opened 2018-05-15 14:21 UTC
Dependency fail n 18.04 Bionic - python-gnomekeyring:

Please fix. Affects all bionic installs.

root@rufus-ubuntu:/home/rufus/Software# ls -lha|grep term
-rw-r--r--  1 rufus rufus  44M May  4 20:53 terminus_1.0.0-alpha.46_amd64.deb
root@rufus-ubuntu:/home/rufus/Software# apt install ./terminus_1.0.0-alpha.46_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'terminus' instead of './terminus_1.0.0-alpha.46_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 terminus : Depends: python-gnomekeyring but it is not installable
E: Unable to correct problems, you have held broken packages.
root@rufus-ubuntu:/home/rufus/Software# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
root@rufus-ubuntu:/home/rufus/Software# uname -a
Linux rufus-ubuntu 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Eugeny** [comment] 2018-05-15 14:50
Duplicate of #339

**Closed by Eugeny** 2018-05-15 14:50 UTC

**Comment by rufusshrestha** [comment] 2018-05-15 14:53
Thanks, awesome terminal, though I hope you can speed up loading.
