### ISSUE TITLE
Only cursor is visible

### ISSUE THREAD

**Issue by c0fe** [Eugeny/terminus#964] opened 2019-05-27 20:36 UTC
I am getting a weird issue where when switching between two active windows the cursor shows up only:

https://i.imgur.com/ejGYP3P.png

**### Steps to Reproduce:**

Open two active SSH session windows
Use Ctrl+Tab to switch between windows

**### Environment:**

**Terminus:** 1.0.78
**OS:** Windows 10 1809
**OS Build:** 17763.503
**Graphics Card:** EVGA GTX 1080 Ti

**Comment by kamkovvv** [comment] 2019-05-28 07:58
The same issue is for me. The issue is in the SSH/CMD/Git-Bash.

Text will appear for me, if I press anything on keyboard or scroll on mouse.

**Comment by Eugeny** [comment] 2019-05-30 12:30
Duplicate of #729

**Closed by Eugeny** 2019-05-30 12:30 UTC
