### ISSUE TITLE
Not functional After Alpha 70

### ISSUE THREAD

**Issue by shaqaruden** [Eugeny/terminus#662] opened 2019-02-11 21:50 UTC
I opened a new terminal and this is all i get.

![Image of Termins](https://i.imgur.com/EPipvSq.png)

Works again when reverting to Alpha 69

**Comment by shaqaruden** [comment] 2019-02-11 21:53
I should point out this is the windows version

**Comment by niktekusho** [comment] 2019-02-12 08:56
I think you should take a look at #653  since there you could also find a workaround until a fix is in place.

**Comment by Eugeny** [comment] 2019-02-12 10:10
Duplicate of #653

**Closed by Eugeny** 2019-02-12 10:10 UTC
