### ISSUE TITLE
[Feature request] Support multiple instances

### ISSUE THREAD

**Issue by hakbra** [Eugeny/terminus#278] opened 2018-01-18 10:34 UTC
I see that multiple instancus is currently not possible, but it is the only feature I am missing from Terminus at the moment. Are there any technical reasons it is not possible now?

**Comment by metastableB** [comment] 2018-02-28 12:53
+1 

It seems you can have multiple windows by `Ctrl + shift + n` , but all of them seem to map to the same instance. Closing one, closes all.

**Comment by Eugeny** [comment] 2018-03-11 19:08
Duplicate of #170

**Closed by Eugeny** 2018-03-11 19:08 UTC
