### ISSUE TITLE
tab content is hidden

### ISSUE THREAD

**Issue by x1nas** [Eugeny/terminus#784] opened 2019-04-25 10:21 UTC
When switching between tabs, their contents are hidden.

Terminus version - after 71.
OS - LinuxMint 19.

**Comment by yousifun** [comment] 2019-04-25 21:18
I'm facing the same problem。switch the tab,contens are hidden。I can only see the content when I enlarge the window border。

![da](https://i.loli.net/2019/04/26/5cc223f998848.gif)

**Comment by edwinosky** [comment] 2019-04-26 21:37
To solve this problem you must change the frontend from xterm to hterm in the Appearance setting

**Comment by yousifun** [comment] 2019-04-26 22:56
> To solve this problem you must change the frontend from xterm to hterm in the Appearance setting

Thanks,It works.

**Comment by Hobart2967** [comment] 2019-05-13 12:17
Hitting enter also is a workaround, or when the terminal generated new content it shows up again.

**Comment by xrr2016** [comment] 2019-05-24 02:00
Same problem

![image](https://user-images.githubusercontent.com/18013127/58297426-455ce780-7e0a-11e9-8f88-49cb79f14196.png)

Terminus version 1.0.77

System:

  - OS: macOS 10.14.4
  - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  - Memory: 3.78 GB / 16.00 GB
  - Shell: 5.7 - /usr/local/bin/zsh

Browsers:
   - Chrome: 74.0.3729.169
   - Chrome Canary: 76.0.3802.0
   - Firefox Developer Edition: 66.0
   - Safari: 12.1

**Comment by Eugeny** [comment] 2019-05-24 08:57
Do you guys have any plugins installed?

**Comment by xrr2016** [comment] 2019-05-24 09:01
> Do you guys have any plugins installed?

no, pure app

**Comment by x1nas** [comment] 2019-05-27 07:50
> Do you guys have any plugins installed?
clean install

workaround: Settings -> Appearance -> Frontend -> hterm

**Comment by Eugeny** [comment] 2019-05-30 12:31
Duplicate of #729

**Closed by Eugeny** 2019-05-30 12:31 UTC
Labels: T: Bug
