### ISSUE TITLE
Restart session in tab

### ISSUE THREAD

**Issue by ChipwizBen** [Eugeny/terminus#1350] opened 2019-08-07 03:08 UTC
If a session dies, it would be good to be able to restart that session by restarting it and preserving the tab (including any text within it) and not having to reopen a new tab. Putty can do this with a right click and an option called "Restart Session".

**Comment by Eugeny** [comment] 2019-08-07 13:19
Duplicate of #761

**Closed by Eugeny** 2019-08-07 13:19 UTC

**Comment by Arichy** [comment] 2022-04-06 15:15
> Duplicate of #761

How can I restart a normal session which is not ssh or telnet?
