### ISSUE TITLE
In this version, When toggle terminal window, app creating new icon as i attached.

### ISSUE THREAD

**Issue by msaistaken** [Eugeny/terminus#3195] opened 2020-12-09 13:31 UTC
![image](https://user-images.githubusercontent.com/62212589/101636124-edadbd80-3a3b-11eb-8593-0d2f2186d3d7.png)

**Comment by masa0612** [comment] 2020-12-23 09:31
I encountered the same problem with the following environment.

Version: 1.0.122
Platform: linux 4.15.0-128-generic
Plugins: none

**Comment by Eugeny** [comment] 2021-04-04 17:54
Duplicate of #1642

**Closed by Eugeny** 2021-04-04 17:54 UTC
