### ISSUE TITLE
clear command leaves visual artifacts behind

### ISSUE THREAD

**Issue by jrhalchak** [Eugeny/terminus#114] opened 2017-07-10 15:59 UTC
I noticed this after running vim in a terminal window.

I'm using `git-bash` on windows with _Fira Code_ as my font and the base16 color scheme.

After I run `clear`, the text previously there is still visible behind the new prompts.

In this case, it was after I quit the vim editor.
![terminus-clear](https://user-images.githubusercontent.com/4794493/28027512-49b4e872-6567-11e7-827a-9bdcf7a56e3b.PNG)

**Comment by Eugeny** [comment] 2017-07-10 16:08
Duplicate of #28

**Closed by Eugeny** 2017-07-10 16:08 UTC

**Comment by jrhalchak** [comment] 2017-07-10 16:09
Ah, sorry. 😞 

I skimmed the issues but thought immediately after posting that I should've done a search.
