### ISSUE TITLE
rz/sz not working

### ISSUE THREAD

**Issue by Leon2018** [Eugeny/terminus#2353] opened 2020-04-07 02:27 UTC
Version: 1.0.105
Platform: win32 10.0.15063
Plugins: none

CentOS release 6.5 (Final) / lrzsz-0.12.20 

Terminal displayed "Offered", noting uploaded.

**Comment by Eugeny** [comment] 2020-04-14 07:22
Duplicate of #2352

**Closed by Eugeny** 2020-04-14 07:22 UTC
