### ISSUE TITLE
Why not support lrzsz?

### ISSUE THREAD

**Issue by RookieOperator** [Eugeny/terminus#1745] opened 2019-11-07 05:37 UTC
Version: 1.0.92
Platform: win32 10.0.17763
Plugins: none

**Comment by baidjay** [comment] 2019-11-07 05:44
When I copy a piece of text，there are extra characters when I paste it，like this:
# vim pod-demo.yaml 
# 0~vim pod-demo.yaml1~

**Comment by Eugeny** [comment] 2019-11-26 14:04
Duplicate of #693

**Closed by Eugeny** 2019-11-26 14:04 UTC
