### ISSUE TITLE
Navigating to Hotkeys from plugins in the settings leave the plugin and hotkey setting in the same page

### ISSUE THREAD

**Issue by sathish25071992** [Eugeny/terminus#674] opened 2019-02-16 13:13 UTC
Hi,

I am seeing a mixed setting page (page containing settings for both hotkey and plugins) if I navigate to hotkeys from plugins.

**Comment by sathish25071992** [comment] 2019-02-16 13:15
![bug](https://user-images.githubusercontent.com/12582334/52900371-0b80b180-321b-11e9-8ba6-e5ef97145d90.jpg)

**Comment by Eugeny** [comment] 2019-02-17 11:21
Duplicate of #517

**Closed by Eugeny** 2019-02-17 11:21 UTC
