### ISSUE TITLE
No double auth to ssh server

### ISSUE THREAD

**Issue by Sakubz** [Eugeny/terminus#482] opened 2018-10-29 10:10 UTC
Version: 1.0.0-alpha.62
Platform: win32 10.0.17134

## Current Behavior

When i log to SSH, this message appear : 

Could not connect: Error: spawn C:\util\pagent.exe ENOENT

## Possible Solution

Add double auth ?

## Steps to Reproduce

1. Create ssh server 
2. add key auth + password auth into serv
3. try to connect with key priv ssh and prompt for password ( masked if possible ) and go connect

## Context (Environment)
i juste want connect to my ssh server

## Suggestions?

Can you add a "explorer" bloc at left ? For search any bookmarked ssh, like mremoteNG :) Thanks for your job !!!

**Comment by johnfonner** [comment] 2018-10-31 18:08
I think this request is for support of multifactor authentication through "SSH connections" function within Terminus.  If that is the case, then I will add my support for this feature.

Most of the servers I connect to require ( either SSH Key  or  password ) and a randomly generated Token from my phone.  Currently, when trying to connect to a server like that, both the SSH Key settings or the password popup box work, but then an error is displayed:

Could not connect: Error:  spawn C:\util\pagent.exe ENOENT

The workaround is just to start a local terminal (e.g. WSL) and ssh from there, but it would be a killer feature to build in multifactor support for SSH connections in the GUI.

**Comment by Eugeny** [comment] 2018-12-15 13:31
Duplicate of #496

**Closed by Eugeny** 2018-12-15 13:31 UTC
