### ISSUE TITLE
Display error when switch tabs

### ISSUE THREAD

**Issue by Sophistt** [Eugeny/terminus#982] opened 2019-05-30 11:58 UTC
Version: 1.0.78
Platform: win32 10.0.17763
Plugins: none

when I switch tabs, there is something wrong in the current window's display. It doesn't show anything until I enter something or move the scroll bar.

![微信图片_20190530195550](https://user-images.githubusercontent.com/26649771/58631374-f08f0480-8314-11e9-85b7-d244ba7197f6.png)

**Comment by Eugeny** [comment] 2019-05-30 12:30
Duplicate of #729

**Closed by Eugeny** 2019-05-30 12:30 UTC
