### ISSUE TITLE
Tray shows multiple terminus logos

### ISSUE THREAD

**Issue by Tbhesswebber** [Eugeny/terminus#3540] opened 2021-03-02 21:10 UTC
Version: 1.0.134
Platform: linux 5.8.0-44-generic
Plugins: none
OS: Ubuntu 20.04

I have the system set up to toggle a docked terminus window with a keybinding and to hide on onBLur.  For some reason, every time I show and hide the app, another terminus logo appears in my taskbar (currently showing 19 of them).

This _could_ be caused by a Gnome Extension that I'm using - [Dash to Panel](https://github.com/home-sweet-gnome/dash-to-panel)

**Comment by Tbhesswebber** [comment] 2021-03-02 22:21
As I think about it, it would be great to have a setting to just turn off the tray icon all together - I didn't see the option anywhere when I dug through the settings.

**Comment by semoog** [comment] 2021-03-07 08:07
Same issue (and here: https://github.com/Eugeny/terminus/issues/319) - 

![image](https://user-images.githubusercontent.com/1973922/110233480-74f6ba00-7ee1-11eb-9c34-3ec56ec0ddde.png)

Linux Mint

**Comment by Eugeny** [comment] 2021-04-04 17:54
Duplicate of #1642

**Closed by Eugeny** 2021-04-04 17:54 UTC
