### ISSUE TITLE
When dragging window it slows my mouse down to a crawl and goes slowly across the screen.

### ISSUE THREAD

**Issue by ProcrastinatingEntrepreneur** [Eugeny/terminus#3213] opened 2020-12-19 05:05 UTC
Version: 1.0.122
Platform: win32 10.0.19042
Plugins: clickable-links, theme-hype

**Comment by ProcrastinatingEntrepreneur** [comment] 2020-12-19 05:08
Only happens on fluent

**Comment by miversen33** [comment] 2020-12-21 17:47
I had the same thing happen. I deleted my config and then uninstalled and reinstalled and the issue was resolved. I know thats not a "correct" solution, however it did work for me. It seems I was using an old config from the last time I used terminus. I wonder if there is something that has changed between the configs for older installations (I tried terminus about a year ago) and current.

**Comment by Eugeny** [comment] 2020-12-27 12:02
Duplicate of #949

**Closed by Eugeny** 2020-12-27 12:02 UTC
