### ISSUE TITLE
SSH Port Forward: EADDRINUSE: address already in use

### ISSUE THREAD

**Issue by wassimsabra** [Eugeny/terminus#2181] opened 2020-02-26 17:05 UTC
SSH   X  Failed to forward port (local) 127.0.0.1:18080 → (remote) 23.45.67.89:8080: Error: listen EADDRINUSE: address already in use 127.0.0.1:18080

The added port forwarding does not show after restarting the application.
If I try to re-added I get the error above, however, the port forwarding is not working.

**Comment by Eugeny** [comment] 2020-03-03 14:28
Duplicate of #2143

**Closed by Eugeny** 2020-03-03 14:28 UTC
