### ISSUE TITLE
Add proxy command to bastions in saved sessions

### ISSUE THREAD

**Issue by dabrazhe** [Eugeny/terminus#769] opened 2019-04-17 09:13 UTC
Could you please add proxy command to bastions (jump boxes) in saved sessions? (Or perhaps let me know how to achieve this.)

The way to call it from command line is like this, given that default identity/private key file is used (the `-i` option).
`ssh user@10.1.1.22 -o "proxycommand ssh -W %h:%p bastionhost"`

It would be great to be able to save it in Settings - SSH - Connections

**Comment by lucawen** [comment] 2019-05-17 18:38
Waiting for this feature :+1:

**Comment by Eugeny** [comment] 2020-02-06 16:32
Duplicate of #737

**Closed by Eugeny** 2020-02-06 16:32 UTC
Labels: Plugin: SSH, T: Enhancement
