### ISSUE TITLE
Dragging Terminus Window is Delayed

### ISSUE THREAD

**Issue by darthsiderius** [Eugeny/terminus#2883] opened 2020-08-10 23:35 UTC
Version: 1.0.116
Platform: win32 10.0.19041
Plugins: none

Just download terminus on my new machine, using ubuntu wsl with windows. When I try to drag the terminus window, it is delayed to go to the new position, it moves at a slower pace than the mouse.

**Comment by kachunkachunk** [comment] 2020-08-13 03:29
This is a Windows issue, unfortunately. See issue #949

**Comment by Eugeny** [comment] 2020-12-27 12:02
Duplicate of #949

**Closed by Eugeny** 2020-12-27 12:02 UTC
