### ISSUE TITLE
a49 not showing anything on windows10

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#387] opened 2018-08-10 09:21 UTC
tried deleting everything in local and roaming directories. nothing changes.

**Comment by Eugeny** [comment] 2018-08-10 09:33
Duplicate of #386, artifacts coming in a couple of minutes

**Comment by princemaple** [comment] 2018-08-10 09:33
sorry, thought I was the first one!

**Comment by princemaple** [comment] 2018-08-10 09:34
thank you for all the new features!

**Closed** 2018-08-10 09:33 UTC
