### ISSUE TITLE
Unbearable drag experience

### ISSUE THREAD

**Issue by dreamer2q** [Eugeny/terminus#2392] opened 2020-04-13 16:12 UTC
Version: 1.0.106
Platform: win32 10.0.19041
Plugins: none

When I click to drag the `terminus` around, it reacts very slow and I have to wait the window moves little by little until the expected postion. Unlike others apps in my computer in which you can drag it everywhere and it reacts very smoothly, I can not operate anything during this slow drag reaction progress.

I do not know it is a common behaviour or just because my computer not configured properly

Any help is appreciated.

![image](https://user-images.githubusercontent.com/56211747/79137067-9ee45100-7de4-11ea-88f8-90717846eaea.png)

**Comment by effgenij** [comment] 2020-04-14 12:06
change background type to blur. I have the same problem with fluent background type.

**Comment by dreamer2q** [comment] 2020-04-14 14:33
> Change background type to blur. I have the same problem with fluent background type.

Thanks a lot. It works.

**Comment by Eugeny** [comment] 2020-07-27 14:15
Duplicate of #949

**Closed by Eugeny** 2020-07-27 14:15 UTC
