### ISSUE TITLE
Update killed existing configuration, leaves terminus unusable

### ISSUE THREAD

**Issue by berndlaser** [Eugeny/terminus#1821] opened 2019-11-26 09:49 UTC
Version: 1.0.94
Platform: win32 10.0.18363

Can't open new terminals - no PS, no CMD, no WSL, nothing.

**Comment by Eugeny** [comment] 2019-11-26 09:51
Fix coming up!

**Comment by Eugeny** [comment] 2019-11-26 09:56
Duplicate of #1822

**Closed by Eugeny** 2019-11-26 09:56 UTC
