### ISSUE TITLE
Additional lines on copy

### ISSUE THREAD

**Issue by StevenKGER** [Eugeny/terminus#313] opened 2018-04-01 00:32 UTC
Hello,

if I want to copy some text which consits more than one line, e.g.:
![Here should be the example](https://i.imgur.com/4VJOWXY.png)

it ends like this:
![Here should be another example](https://i.imgur.com/foSyYG3.png)

I am using the paste function by using a rightclick, which I adjusted in the settings of Terminus.
For now I am using the version 1.0.0-alpha.44 with WSL as default terminal.

**Comment by Eugeny** [comment] 2018-04-01 17:49
This is a duplicate of #293, but I was so far unable to reproduce this or pinpoint a specific environment where this happens.

**Closed by Eugeny** 2018-04-01 17:49 UTC

**Comment by ohouigheighi** [comment] 2018-04-18 21:33
hyper.is used to have this same issue, perhaps some of the posts on this thread will help: https://github.com/zeit/hyper/issues/654

Particularly this post by @alexjmoore: https://github.com/zeit/hyper/issues/654#issuecomment-342249944

> "It is because on Windows the end of a line is signified by a carriage return (\r) and a newline (\n), whereas on *nix systems those are two separate end of line characters, hence why when you paste out of the windows clipboard you get the two new lines, the intended one and an extra one - causing the 'space' between the lines. General fix I think is to simply swap occurrences of "\r\n" with a single "\n" on a paste action when on a windows platform."

Would love to have this issue resolved Terminus on Windows.

**Comment by Eugeny** [comment] 2018-04-19 00:16
@ohouigheighi please see if v45 (release a couple of hours ago) solves it for you

**Comment by ohouigheighi** [comment] 2018-04-19 19:57
@Eugeny Definitely appears to fixed, thank you very much. Great job
