### ISSUE TITLE
Going back to a running terminal tab shows only a blank entry

### ISSUE THREAD

**Issue by couchcamote** [Eugeny/terminus#1246] opened 2019-07-17 05:02 UTC
Version: 1.0.85
Platform: win32 10.0.16299
Plugins: none

Going back to another tab with running process but the terminal is blank. It will only refresh if you minimize/maximize the Terminus window.

**Comment by Eugeny** [comment] 2019-07-17 06:54
Duplicate of #729

**Closed by Eugeny** 2019-07-17 06:54 UTC
