### ISSUE TITLE
Shows error mesage "Can't resolve all parameters for URLHandler" after strartup

### ISSUE THREAD

**Issue by AndriyKalashnykov** [Eugeny/terminus#4032] opened 2021-06-22 13:54 UTC
After startup shows error message windows with following content:

Terminus could not start with your plugins, so all third party plugins have been disabled in this session. The error was:
Can't resolve all parameters for URLHandler: (?).

version 1.0.140, OS: Ubuntu 21.04

**Comment by Eugeny** [comment] 2021-06-22 14:01
Duplicate of #4013

**Closed by Eugeny** 2021-06-22 14:01 UTC
