### ISSUE TITLE
SSH connection failed when using saved password

### ISSUE THREAD

**Issue by SovietSword** [Eugeny/terminus#3110] opened 2020-10-28 11:07 UTC
**I am using Terminus on Windows 10 for SSH connection. The "Authencation" option is set as "password".** 

![terminus1](https://user-images.githubusercontent.com/47520284/97427570-b681c200-194f-11eb-8566-55e0200ec072.png)

**But when I try to connect, Terminus tries to use private key and causes an error.**

![terminus2](https://user-images.githubusercontent.com/47520284/97427573-b7b2ef00-194f-11eb-87e8-f1547ac97f8b.png)

**And if I delete ~/.ssh/id_rsa and ~/.ssh/id_rsa.pub, Termius works right then.**

![terminus3](https://user-images.githubusercontent.com/47520284/97427575-b84b8580-194f-11eb-910d-d8a4814c3b37.png)

**I am quite confused. Is there something wrong with my environment, or are there bugs with Terminus's authencation logic?**

**Comment by isdqwq** [comment] 2020-11-04 08:10
![Uploading image.png…]()

**Comment by rbukovansky** [comment] 2020-11-23 22:02
Yeah, I have already reported this issue in #2968 😊

Unfortunately, it seems like another great and awesome open source project dead in the water... 😢 Or am I mistaken, @Eugeny? 🤷

**Comment by Eugeny** [comment] 2020-12-06 16:42
Duplicate of #2968

**Closed by Eugeny** 2020-12-06 16:42 UTC

**Comment by rbukovansky** [comment] 2020-12-07 18:49
Problem solved with the latest AppVeyor build! 🍾
