### ISSUE TITLE
Can't enter anything through keyboard. Mouse works

### ISSUE THREAD

**Issue by guoicq** [Eugeny/terminus#3399] opened 2021-02-02 18:41 UTC
Version: 1.0.128   Version: 1.0.129  and Version: 1.0.130
Platform: win32 10.0.14393
Plugins: none

I rollback to Version: 1.0.127 which works fine.

**Comment by joaoreis13** [comment] 2021-02-03 00:03
Same for me. I'm attaching the console output. Every time I type a key, it throws the following error:

`Uncaught Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:456)
    at WindowsTerminal._doWrite (C:\Program Files\Terminus\resources\app.asar\node_modules\@terminus-term\node-pty\lib\windowsTerminal.js:114)
    at WindowsTerminal._defer (C:\Program Files\Terminus\resources\app.asar\node_modules\@terminus-term\node-pty\lib\windowsTerminal.js:156)
    at WindowsTerminal._write (C:\Program Files\Terminus\resources\app.asar\node_modules\@terminus-term\node-pty\lib\windowsTerminal.js:111)
    at WindowsTerminal.Terminal.write (C:\Program Files\Terminus\resources\app.asar\node_modules\@terminus-term\node-pty\lib\terminal.js:81)
    at Session.write (C:\Program Files\Terminus\resources\builtin-plugins\terminus-terminal\dist\index.js:12988)
    at TerminalTabComponent.sendInput (C:\Program Files\Terminus\resources\builtin-plugins\terminus-terminal\dist\index.js:8736)
    at SafeSubscriber._next (C:\Program Files\Terminus\resources\builtin-plugins\terminus-terminal\dist\index.js:8964)
    at SafeSubscriber.__tryOrUnsub (C:\Program Files\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205)
    at SafeSubscriber.next (C:\Program Files\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143)

`

[TerminusFailure.log](https://github.com/Eugeny/terminus/files/5915173/TerminusFailure.log)

**Comment by Eugeny** [comment] 2021-02-13 14:03
Duplicate of #3397

**Closed by Eugeny** 2021-02-13 14:03 UTC
