### ISSUE TITLE
Terminus goes out of screen when dock option is set up within the software

### ISSUE THREAD

**Issue by Rexcrazy804** [Eugeny/terminus#427] opened 2018-09-20 13:37 UTC
i had to delete everything terminus to get the software start working again

**Comment by iceMatcha** [comment] 2018-09-21 03:01
i had the same issue！！！

**Comment by Juneuly** [comment] 2018-09-25 04:47
i had the same issue, too!!!!!!

**Comment by WuChouRao** [comment] 2018-10-21 07:32
same problem

**Comment by osimbarhew** [comment] 2018-10-24 15:23
Also same issue but you don't need to reinstall the app, just remove the "dock" line from the config.yaml file.

On Windows you can find it at `C:\Users\<user>\AppData\Roaming\Terminus\config.yaml`

**Comment by lpreiner** [comment] 2018-11-10 04:53
I had this problem as well, and was able to fix it by modifying both the config.yaml file mentioned by @osimbarhew as well as window.json.

**Comment by Rexcrazy804** [comment] 2019-01-09 05:16
Yeah better try not to change the dock setting in future

**Comment by glen-84** [comment] 2019-03-10 15:41
Duplicate of #364?

**Comment by Eugeny** [comment] 2019-03-10 17:06
Duplicate of #364

**Closed by Eugeny** 2019-03-10 17:06 UTC

**Comment by Rexcrazy804** [comment] 2019-03-10 17:09
Sorry haven't seen #364 thank you for closing this pull request.
