### ISSUE TITLE
Clink running as admin displays characters incorrectly.

### ISSUE THREAD

**Issue by jack1142** [Eugeny/terminus#1265] opened 2019-07-19 00:07 UTC
Version: 1.0.87
Platform: win32 10.0.18362
Plugins: none

Cmder profile with "Run as administrator" checked (also notice the cursor in wrong place and scrollbar showing even though it's not necessary):
![Terminus_s88qNZJA2Z](https://user-images.githubusercontent.com/6032823/61500009-908a1580-a9c9-11e9-9166-1c313174a8be.png)

Cmder profile with "Run as administrator" unchecked:
![Terminus_PUQqVu2DpP](https://user-images.githubusercontent.com/6032823/61500023-aac3f380-a9c9-11e9-8583-a7461fe90fe6.png)

The issue doesn't happen if I run Terminus as Administrator instead of using the "Run as administrator" option in profile settings

**Comment by jack1142** [comment] 2019-07-19 00:10
Edited title, because it looks like same thing happens when using clink provided with Terminus.
![Terminus_2crQS0JjKn](https://user-images.githubusercontent.com/6032823/61500196-6b49d700-a9ca-11e9-8b91-6dbea0d73110.png)
![Terminus_qjsaDGrSBN](https://user-images.githubusercontent.com/6032823/61500198-6b49d700-a9ca-11e9-8ca9-0e3971eedc95.png)

**Comment by jack1142** [comment] 2019-09-20 12:45
This issue still occurs on Terminus 1.0.91

**Comment by kvdrrrrr** [comment] 2019-09-23 07:13
This also happens with extended ASCII characters. Moreover, the arrow keys seem to be broken as well: pressing left arrow key results in `[D`, right arrow key results in `[C`. If you need a workaround for this issue, run `Terminus.exe` itself as administrator. All future cmd.exe prompts inside Terminus instance will run with admin privileges.

**Comment by laundmo** [comment] 2020-01-31 09:52
@kvdrrrrr the issue with arrow keys isn't fixed by running terminus as admin when the "run as administrator" profile option is checked for a profile. it will still mess up the arrow keys.

**Comment by KhimairaCrypto** [comment] 2020-05-24 02:58
I am using the latest release. I created a new Shell profile as you can see in the image attached to this post. I am experiencing the same issue with the characters, and CTRL-R does not seams to work. I am wondering if the reason why I am experiencing this issues is because the environment is set to: TERM -> cywin

![image](https://user-images.githubusercontent.com/36352470/82744578-dec42e00-9dbd-11ea-9a35-71ee84ae0d42.png)

**Comment by Eugeny** [comment] 2020-06-14 15:26
Duplicate of #691

**Closed by Eugeny** 2020-06-14 15:26 UTC
Labels: OS: Windows, S: Confirmed, T: Bug
