### ISSUE TITLE
bug of display

### ISSUE THREAD

**Issue by PiousJester** [Eugeny/terminus#1098] opened 2019-06-21 01:34 UTC
Version: 1.0.82
Platform: win32 10.0.18362
Plugins: none

![Snipaste_2019-06-21_09-31-41](https://user-images.githubusercontent.com/50016588/59891405-97902900-9407-11e9-9098-152b332b41c3.png)
![Snipaste_2019-06-21_09-31-55](https://user-images.githubusercontent.com/50016588/59891410-9e1ea080-9407-11e9-9f95-4842b44a5587.png)

**Comment by Eugeny** [comment] 2019-06-21 06:28
Duplicate of #729

**Closed by Eugeny** 2019-06-21 06:28 UTC
