### ISSUE TITLE
Posh git integration for administrator consoles?

### ISSUE THREAD

**Issue by ezr0** [Eugeny/terminus#2605] opened 2020-05-20 08:25 UTC
Just wondering if theres any scope for posh git integration? Currently if you run powershell in administrator the branches show strange characters? Also if you press up or down to go through previous commands it shows strange characters.

![image](https://user-images.githubusercontent.com/36925169/82423488-ba91e580-9a7b-11ea-86dd-15073fc414f6.png)

In a normal console window its fine:
![image](https://user-images.githubusercontent.com/36925169/82423558-d1383c80-9a7b-11ea-9b17-db0e463fe05f.png)

**Comment by Eugeny** [comment] 2020-06-14 16:47
Duplicate of #654

**Closed by Eugeny** 2020-06-14 16:47 UTC
