### ISSUE TITLE
not working properly with wsl / Ubuntu-18.04

### ISSUE THREAD

**Issue by mskyspet** [Eugeny/terminus#671] opened 2019-02-15 10:33 UTC
Settings->HotKey not display correctly, show emtpy items as below.
![tim 20190215175843](https://user-images.githubusercontent.com/1519187/52851003-f3902b80-314f-11e9-93c7-ded4ac47116d.png)

debug console log:

> C:\Users\MiaoPeng\AppData\Local\terminus\app-1.0.71\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15313 ERROR TypeError: Cannot read property '04' of undefined
    at SettingsTabComponent.getHotkey (C:\Users\MiaoPeng\AppData\Local\terminus\app-1.0.71\resources\builtin-plugins\terminus-settings\dist\index.js:1056)
    at Object.eval [as updateDirectives] (SettingsTabComponent.ngfactory.js:1242)
    at Object.updateDirectives (C:\Users\MiaoPeng\AppData\Local\terminus\app-1.0.71\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:23131)
    at checkAndUpdateView (C:\Users\MiaoPeng\AppData\Local\terminus\app-1.0.71\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22784)
    at callViewAction (C:\Users\MiaoPeng\AppData\Local\terminus\app-1.0.71\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:23025)
    at execEmbeddedViewsAction (C:\Users\MiaoPeng\AppData\Local\terminus\app-1.0.71\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22988)
    at checkAndUpdateView (C:\Users\MiaoPeng\AppData\Local\terminus\app-1.0.71\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22785)
    at callViewAction (C:\Users\MiaoPeng\AppData\Local\terminus\app-1.0.71\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:23025)
    at execEmbeddedViewsAction (C:\Users\MiaoPeng\AppData\Local\terminus\app-1.0.71\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22988)
    at checkAndUpdateView (C:\Users\MiaoPeng\AppData\Local\terminus\app-1.0.71\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22785)

possible reason:
![tim 20190215183111](https://user-images.githubusercontent.com/1519187/52851025-0276de00-3150-11e9-9724-c0e9d6872468.png)

Version: 1.0.71
Platform: win64 10.0.17763
Plugins: default

**Comment by Eugeny** [comment] 2019-02-17 11:20
Duplicate of #517

**Closed by Eugeny** 2019-02-17 11:20 UTC
