### ISSUE TITLE
Where is the button of enable clipboard from remote(ssh)

### ISSUE THREAD

**Issue by trueshot86** [Eugeny/terminus#2146] opened 2020-02-19 05:40 UTC
Version: 1.0.103
Platform: win32 10.0.18363
Plugins: none

I could not paste host'sclipboard when I copied from remote by tmux.
Most terminal application has a menu of enable clipboard from remote.
Would you tell me the location of that ?

**Comment by Eugeny** [comment] 2020-04-19 14:48
Duplicate of #2019

**Closed by Eugeny** 2020-04-19 14:48 UTC
