### ISSUE TITLE
SSH Terminal does not 'wrap' text correctly

### ISSUE THREAD

**Issue by richstokes** [Eugeny/terminus#480] opened 2018-10-28 16:43 UTC
It's going off the bottom of my screen. I have to issue a 'reset' command and start again.

It's like the program doesn't know how big the size of its own window is and text is falling off the bottom.

Windows 10 + terminus-1.0.0-alpha.62-portable.exe

**Comment by richstokes** [comment] 2018-10-28 16:48
Played about a bit more, seems to happen when the app is moved between screens with two different resolutions

**Comment by Eugeny** [comment] 2018-12-28 11:37
@richstokes do these displays also have different scaling factors (DPI)?

**Comment by richstokes** [comment] 2018-12-28 11:38
They do, yep. 100% and 120%

**Comment by Eugeny** [comment] 2018-12-28 11:47
Could this be a duplicate of #576 then?

**Comment by richstokes** [comment] 2018-12-28 11:47
Almost certainly :-)

**Closed** 2018-12-28 11:48 UTC
Labels: S: Duplicate
