### ISSUE TITLE
Cant use app hotkeys in terminal window

### ISSUE THREAD

**Issue by crutchcorn** [Eugeny/terminus#677] opened 2019-02-18 19:37 UTC
When using Windows 10 and Terminus 1.0.71, I am unable to use Ctrl+Tab or Shift+Ctrl+Right arrow and others to shift tab windows or do various hotkeys. They're instead passed to the terminal window. I'd love to have hotkeys have the option of overwriting the terminal for keyboard focus for hotkey recognition

**Comment by Eugeny** [comment] 2019-02-19 22:50
Duplicate of #658

**Closed by Eugeny** 2019-02-19 22:51 UTC
