### ISSUE TITLE
background colors fonts w/ Acrylic - do not display correctly

### ISSUE THREAD

**Issue by lgordnier** [Eugeny/terminus#1630] opened 2019-10-15 13:41 UTC
Version: 1.0.92
Platform: win32 10.0.18362
Plugins: clickable-links, save-output

When enabling Acrylic background - fonts with a non-default background color (highlight) do not display properly. the font and background color are the same - so you see blocks, and not letters.

with Acrylic enabled:
![image](https://user-images.githubusercontent.com/3386061/66836742-e2422d80-ef2f-11e9-859a-b29b2a03ecc2.png)

without Acrylic enabled (how it should be):
![image](https://user-images.githubusercontent.com/3386061/66836775-f1c17680-ef2f-11e9-935e-6e7dbc752deb.png)

**Comment by timotejroiko** [comment] 2019-11-08 01:15
so this is why... and i though the problem was the theme colors...

**Comment by kachunkachunk** [comment] 2019-11-26 09:53
You can kind of get around it with Appearance -> From Color Scheme instead of Theme, but it isn't quite the way things ought to look, I guess.

**Comment by Eugeny** [comment] 2019-11-26 09:54
Duplicate of #646

**Closed by Eugeny** 2019-11-26 09:54 UTC
