### ISSUE TITLE
Transparency Still Doesn't Work On Linux

### ISSUE THREAD

**Issue by yonderbread** [Eugeny/terminus#2796] opened 2020-07-17 20:04 UTC
Even after the new update, the transparency feature still does not work.

**System Specs:**
- > Linux Mint 20 (4.6.6) (Cinnamon)
- > GPU: GeForce GTX 760
- > CPU: i5-4670K

![Screenshot from 2020-07-17 13-04-19](https://user-images.githubusercontent.com/33736622/87826602-0d92d980-c82e-11ea-93e5-250390bebbdb.png)

(Yes I have changed the opacity slider, still nothing)

**Comment by loscil06** [comment] 2020-07-31 17:46
I confirm it also doesn't work in Ubuntu 20.04 
![image](https://user-images.githubusercontent.com/40837050/89062275-c4fa1680-d32b-11ea-85d0-fbc1850f96b4.png)

**Comment by Eugeny** [comment] 2020-07-31 19:10
Duplicate of #832

**Closed by Eugeny** 2020-07-31 19:10 UTC
