### ISSUE TITLE
[Bug] Window move so slow when background is Fluent

### ISSUE THREAD

**Issue by PMExtra** [Eugeny/terminus#1130] opened 2019-06-25 15:33 UTC
There is a screen recording gif (16.3MB, please wait for loading):
![ScreenRecording](https://github.com/PMExtra/ImageHost/raw/master/Issues/Eugeny_Terminus_%231130.GIF)

Notes:
1. Move window with `Blur` background, all going well.
2. Move window with `Fluent` background, the window moved so slow, and the window was still moving followed the previous track when I stopped my mouse. There were 2 cursors on my screen at the moment., one of the real cursor, another one of the delayed cursor that was pinned on the window.

Maybe caused by Hi-DPI (my screen is 3840x2160@60Hz 150% DPI scaling)

**Comment by Eugeny** [comment] 2019-06-25 16:28
Duplicate of #949 - this is a windows bug, see https://aka.ms/AA4pzyf

**Closed by Eugeny** 2019-06-25 16:28 UTC
