### ISSUE TITLE
Can't open settings intermittently

### ISSUE THREAD

**Issue by qqz** [Eugeny/terminus#1792] opened 2019-11-20 18:15 UTC
Version: 1.0.92
Platform: win32 10.0.17763
Plugins: none

**Comment by dangerose** [comment] 2019-11-21 08:47
same

**Comment by xwyam** [comment] 2019-11-24 09:01
save with terminus version 1.0.92, windows version windows 10 pro x64 17763.678

**Comment by Eugeny** [comment] 2019-11-26 13:48
Duplicate of #1785

**Closed by Eugeny** 2019-11-26 13:48 UTC
