### ISSUE TITLE
grep on larger file (270k) freezes terminus

### ISSUE THREAD

**Issue by mariusa** [Eugeny/terminus#3590] opened 2021-03-13 18:58 UTC
With attached file, run
`grep appo app.txt`

Results are shown in terminal, then back to cursor. Then terminus freezes. CPU fan starts and can't do anything else within terminus, not even close it from window toolbar.

This happens 100% of time with grep on larger text files.
[app.txt](https://github.com/Eugeny/terminus/files/6135369/app.txt)

**Comment by clarkwang** [comment] 2021-03-15 11:33
I cannot reproduce with v1.0.135 on macos and win10 (in cygwin or ssh to a linux).

**Comment by clarkwang** [comment] 2021-03-17 11:57
May be the same issue as #3604.

**Comment by max1c** [comment] 2021-03-17 15:40
> May be the same issue as #3604.

Yes, this definitely looks like the same issue.

**Comment by Eugeny** [comment] 2021-03-23 18:26
Duplicate of #3604

**Closed by Eugeny** 2021-03-23 18:26 UTC
