### ISSUE TITLE
Best way to use Horizontal/Vertical panes

### ISSUE THREAD

**Issue by mrananderson** [Eugeny/terminus#218] opened 2017-10-09 18:03 UTC
I tried tmux but it doesnt seem to be working.
Any guidance would be appreciated.

**Comment by viniciusarcanjo** [comment] 2018-01-21 14:48
+1

**Comment by Eugeny** [comment] 2018-03-11 19:13
You can use tmux if you remove all `Ctrl-A` hotkeys from Settings. Otherwise, duplicate of #49

**Closed by Eugeny** 2018-03-11 19:13 UTC
