### ISSUE TITLE
CTRL + L clearing

### ISSUE THREAD

**Issue by CerealKiller97** [Eugeny/terminus#1384] opened 2019-08-13 10:45 UTC
Version: 1.0.87
Platform: win32 10.0.18362
Plugins: scrollbar, shell-selector, theme-hype

When I want to clear screen with CTRL + L it makes a weird move it jumps up and down terminal. With clear command works perfectly.

**Comment by Eugeny** [comment] 2019-09-02 11:10
Duplicate of #1352

**Closed by Eugeny** 2019-09-02 11:10 UTC
