### ISSUE TITLE
Incorrect work ssh

### ISSUE THREAD

**Issue by oxionex** [Eugeny/terminus#558] opened 2018-12-12 19:38 UTC
Good day

If you go to the server via ssh, then try to go to the next server via ssh, the terminal window hangs. The example in the screenshot:

https://prnt.sc/lu5wgv

OS: Windows 10 x64 Version 1809 build 17763.194
Terminus: 1.0.65-portable

**Comment by Eugeny** [comment] 2018-12-15 13:31
Duplicate of #496

**Closed by Eugeny** 2018-12-15 13:31 UTC
