### ISSUE TITLE
SSH connection always tries Key instead of Password

### ISSUE THREAD

**Issue by rbukovansky** [Eugeny/terminus#2968] opened 2020-09-03 15:33 UTC
Version: 1.0.120
Platform: win32 10.0.17134
Plugins: none

Hi,
I am freaking loving Terminus so far, but unfortunately, there is a small issue. When I open a new SSH connection, Terminus tries to authenticate with my SSH key instead of the password that's selected in settings
![terminus_ssh_connection](https://user-images.githubusercontent.com/1004491/92135690-5f59e800-ee0b-11ea-946e-e871558c30b9.png)
![terminus_ssh_connection_settings](https://user-images.githubusercontent.com/1004491/92135692-608b1500-ee0b-11ea-8c48-0ef4afb95ba9.png)

We are not using SSH keys to authenticate to our servers. So, what am I doing wrong?

Thank you.

Regards,
Richard Bukovansky

**Comment by rbukovansky** [comment] 2020-09-05 07:13
@bes-internal You mean directly on our SSH server? I can't touch that (I'm not admin) and in PuTTY or MobaXterm this issue is not happening. 

![image](https://user-images.githubusercontent.com/1004491/92300033-f338ca80-ef57-11ea-9718-64a52ab4ea56.png)

**Comment by bes-internal** [comment] 2020-09-05 10:35
![image](https://user-images.githubusercontent.com/2046529/92303328-681dfb80-ef7c-11ea-87c6-3a259fc4c10d.png)
terminus does not insert the (saved) password in the keyboard-interactive method, as it might seem

**Comment by rbukovansky** [comment] 2020-09-05 12:16
So, that option is there why then? 🤔 Or are you acknowledging it's a bug in Terminus? 🤷‍♂️

**Comment by bes-internal** [comment] 2020-09-05 20:58
This option (authentication password) and setting and save password below is a special method that must be enabled on the server side throught `PasswordAuthentication yes` in `/etc/ssh/sshd_config`.  Usually this option is disabled, as in your case. The saved password is not used when auth check interactive method. 
The only bug here is probably a change in behavior compared to past releases, but this is so important.
This bug is duplicate of #1790

**Comment by rbukovansky** [comment] 2020-09-10 09:54
Special method? What's special on this password authentication? 😮 That's standard username&password authentication, isn't it?
If so, then again, we do have that enabled (!), we wouldn't be able to log into that server (actually all servers) otherwise. See the PuTTY screenshot... That's username&password authenticated.

**Comment by bes-internal** [comment] 2020-09-10 10:47
> Special method? What's special on this password authentication?

We communicate in terms of SSH:

- Password (this method is disabled on your server)
- Public-Key (fails)
- Keyboard-Interactive (the password saved in the interface is not inserted here! the rest of the software applies the password here. Terminus Must be improved to do it as usual for people. See #1790 )
- others...

P.S open setting - debugging - open dev tools  and connect to ssh server:
![Screenshot_3](https://user-images.githubusercontent.com/2046529/92719531-f1ae3e80-f36b-11ea-8be8-07db497d895c.png)

**Comment by rbukovansky** [comment] 2020-09-10 14:42
I don't see that "Server does not support auth method password" there:

![image](https://user-images.githubusercontent.com/1004491/92747439-7d33c980-f384-11ea-8cfc-e08ce8484601.png)

**Comment by rbukovansky** [comment] 2020-09-10 22:27
BTW I still think you are missing my point... I do get logged in to that server with my in Terminus saved password after it tries SSH key authentication, and I'm definitely not typing my password to get in. So, Terminus has to use that saved password, that's for sure, what I'm not sure, why it tries to use my SSH key first when I selected Saved password in the definition of that SSH connection. I would really like if Terminus could just use the authentication method chosen, in my case, Saved password, and skip all the rest.

**Comment by rbukovansky** [comment] 2020-09-17 09:24
@Eugeny Would be please possible you could take a look? Thank you very much.

**Comment by bes-internal** [comment] 2020-09-17 11:11
I cannot reproduce your case. When saved ssh key ask about passphase (with saved password too) it does it interactively:
![image](https://user-images.githubusercontent.com/2046529/93462625-45320680-f8ef-11ea-8c96-086fff102398.png)
Try to recreate this entry in the ssh section.

@Eugeny bug: terminus ignores auth mode selector switch and always do auto!

**Comment by rbukovansky** [comment] 2020-09-28 11:34
@bes-internal Well, I don't have SSH key entered. Terminus with auto mode autoselects my standard SSH key ~/.ssh/id_rsa and asks for my passphrase. If I enter the correct passphrase, Terminus tries that SSH key, which is rejected, and then it continues with my stored password (see the very first screenshot). If I don't enter the passphrase for the SSH key, the connection fails with some error and does not continue with using the stored password.

**Comment by zhudong-mfcgd** [comment] 2020-11-16 22:54
Same issue here. Although I set it to use `Password` to login, it always try to use my `~/.ssh/id_rsa` to login. Of course, it fails every time.

**Closed** 2020-12-06 16:43 UTC

**Comment by rbukovansky** [comment] 2020-12-07 18:47
I can confirm the problem has been resolved in the latest AppVeyor build.

Thank you, @Eugeny!
