### ISSUE TITLE
Resizing problems!

### ISSUE THREAD

**Issue by udv-code** [Eugeny/terminus#2693] opened 2020-06-10 13:36 UTC
This ![GIF](https://user-images.githubusercontent.com/46484314/84274543-ad2ac100-ab38-11ea-9d56-90517a98b702.gif) shows wtf-like behaviour of terminus window on windows. It's not matter which window type I use.

**Comment by verhyppo** [comment] 2020-06-13 14:03
Can you provide some more information like the Windows version?

**Comment by udv-code** [comment] 2020-06-13 15:30
I upgraded windows one day ago. Current version is 1909 (Build 18363.900)

**Comment by verhyppo** [comment] 2020-06-13 22:01
It's strange, I just tried it on my Windows VM and I didn't experienced the same problem. Can you please open the debugger and see if there is something that is throwing strange exception while resizing? 
Are you using the Terminus version downloaded from here or did you recompiled it? Maybe something related to the screen resolution?

**Comment by udv-code** [comment] 2020-06-14 06:22
No exceptions are raised.

I think issue #2687 is about that too.
I'll try to debug app later. Maybe I'll find the fix!

**Comment by washicjr** [comment] 2020-06-16 21:26
I experience similar issues after setting the background type to "fluent".  With the background set to "Blur" this behavior does not exist for me.

**Comment by taupehat** [comment] 2020-06-18 23:16
Agreed - setting to "blur" resolves the issue for me as well.

**Comment by Eugeny** [comment] 2020-07-27 14:17
Duplicate of #2469, #949

**Closed by Eugeny** 2020-07-27 14:17 UTC
