### ISSUE TITLE
[bug] default path setting 

### ISSUE THREAD

**Issue by VVVVictorJ** [Eugeny/terminus#2258] opened 2020-03-15 13:05 UTC
I set the default path in the settings,like that, ``` C:\Users\vanPersie\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\flask-server\```,but when I open the new console. It will be redirected to 
the root directory of wsl,like this 
![image](https://user-images.githubusercontent.com/38826071/76701932-a4c11680-6700-11ea-81c3-ebe7d8685212.png)
 I had read the #47,but it's not help for me.

**Comment by Eugeny** [comment] 2020-03-21 20:14
Duplicate of #271

**Closed by Eugeny** 2020-03-21 20:14 UTC
