### ISSUE TITLE
Bad drag behavior with Fluent background type

### ISSUE THREAD

**Issue by basteez** [Eugeny/terminus#1270] opened 2019-07-19 13:24 UTC
I noticed that if you apply the Acrylic bg + Fluent bg type and you try to drag the window across the desktop, it moves in a strange way, like the mouse become unresponsive for some ms.

Unfortunately can't record this with a screen recorder.

Tried on a i7 + Intel HD 5500

**Comment by Eugeny** [comment] 2019-07-19 13:31
Duplicate of #1130

**Closed by Eugeny** 2019-07-19 13:31 UTC
