### ISSUE TITLE
Some time the settings can not be opened.

### ISSUE THREAD

**Issue by birdmanmandbir** [Eugeny/terminus#1665] opened 2019-10-22 16:33 UTC
Version: 1.0.92
Platform: win32 10.0.18362
Plugins: none

Some time the settings can not be opened. (no response)

**Comment by Eugeny** [comment] 2019-10-23 04:18
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by marcinbojko** [comment] 2019-10-23 08:38
this is is:
```
errors.ts:35 ERROR YAMLException {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d…27:9)↵    at dump (webpack-internal:///266:817:7)"}
defaultErrorLogger @ errors.ts:35
ErrorHandler.handleError @ error_handler.ts:51
dispatchEvent @ util.ts:137
(anonymous) @ element.ts:200
(anonymous) @ dom_renderer.ts:52
ZoneDelegate.invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:423
onInvokeTask @ ng_zone.ts:262
ZoneDelegate.invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:422
Zone.runTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:195
ZoneTask.invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:498
invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:1744
globalZoneAwareCallback @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:1770
errors.ts:35 ERROR YAMLException {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d…27:9)↵    at dump (webpack-internal:///266:817:7)"}
defaultErrorLogger @ errors.ts:35
ErrorHandler.handleError @ error_handler.ts:51
dispatchEvent @ util.ts:137
(anonymous) @ element.ts:200
(anonymous) @ dom_renderer.ts:52
ZoneDelegate.invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:423
onInvokeTask @ ng_zone.ts:262
ZoneDelegate.invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:422
Zone.runTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:195
ZoneTask.invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:498
invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:1744
globalZoneAwareCallback @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:1770
errors.ts:35 ERROR YAMLException {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d…27:9)↵    at dump (webpack-internal:///266:817:7)"}
defaultErrorLogger @ errors.ts:35
ErrorHandler.handleError @ error_handler.ts:51
dispatchEvent @ util.ts:137
(anonymous) @ element.ts:200
(anonymous) @ dom_renderer.ts:52
ZoneDelegate.invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:423
onInvokeTask @ ng_zone.ts:262
ZoneDelegate.invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:422
Zone.runTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:195
ZoneTask.invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:498
invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:1744
globalZoneAwareCallback @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:1770
```

**Comment by jaques-sam** [comment] 2019-10-23 13:16
I'm having the same issue on Windows 10.

**Comment by birdmanmandbir** [comment] 2019-10-24 18:47
C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR YAMLException {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d…27:9)↵    at dump (webpack-internal:///266:817:7)"}mark: undefinedmessage: "unacceptable kind of an object to dump [object Undefined]"name: "YAMLException"reason: "unacceptable kind of an object to dump [object Undefined]"stack: "YAMLException: unacceptable kind of an object to dump [object Undefined]↵    at writeNode (webpack-internal:///266:756:13)↵    at writeBlockMapping (webpack-internal:///266:634:10)↵    at writeNode (webpack-internal:///266:727:9)↵    at writeBlockSequence (webpack-internal:///266:521:9)↵    at writeNode (webpack-internal:///266:740:9)↵    at writeBlockMapping (webpack-internal:///266:634:10)↵    at writeNode (webpack-internal:///266:727:9)↵    at writeBlockMapping (webpack-internal:///266:634:10)↵    at writeNode (webpack-internal:///266:727:9)↵    at dump (webpack-internal:///266:817:7)"__proto__: Error
defaultErrorLogger @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768
ErrorHandler.handleError @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15816
dispatchEvent @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:20580
(anonymous) @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21023
(anonymous) @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:1073
ZoneDelegate.invokeTask @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423
onInvokeTask @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334
ZoneDelegate.invokeTask @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:422
Zone.runTask @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:195
ZoneTask.invokeTask @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:498
invokeTask @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1744
globalZoneAwareCallback @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1770

**Comment by birdmanmandbir** [comment] 2019-10-24 18:48
C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR YAMLException {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d…27:9)↵    at dump (webpack-internal:///266:817:7)"}mark: undefinedmessage: "unacceptable kind of an object to dump [object Undefined]"name: "YAMLException"reason: "unacceptable kind of an object to dump [object Undefined]"stack: "YAMLException: unacceptable kind of an object to dump [object Undefined]↵    at writeNode (webpack-internal:///266:756:13)↵    at writeBlockMapping (webpack-internal:///266:634:10)↵    at writeNode (webpack-internal:///266:727:9)↵    at writeBlockSequence (webpack-internal:///266:521:9)↵    at writeNode (webpack-internal:///266:740:9)↵    at writeBlockMapping (webpack-internal:///266:634:10)↵    at writeNode (webpack-internal:///266:727:9)↵    at writeBlockMapping (webpack-internal:///266:634:10)↵    at writeNode (webpack-internal:///266:727:9)↵    at dump (webpack-internal:///266:817:7)"__proto__: Error
defaultErrorLogger @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768
ErrorHandler.handleError @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15816
dispatchEvent @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:20580
(anonymous) @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21023
(anonymous) @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:1073
ZoneDelegate.invokeTask @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423
onInvokeTask @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334
ZoneDelegate.invokeTask @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:422
Zone.runTask @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:195
ZoneTask.invokeTask @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:498
invokeTask @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1744
globalZoneAwareCallback @ C:\Users\Hasee\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1770

**Comment by StormYudi** [comment] 2019-11-04 10:22
Same issue on Windows 10.

**Comment by Zebraslive** [comment] 2019-11-06 02:28
same here windows 7.
can't get the settings to save for ssh connections or toggle paste on right click.

**Comment by Eugeny** [comment] 2019-11-06 11:47
It looks like for some reason your config data gets corrupted. Does restarting Terminus allow you to open settings immediately? Is there anything obviously wrong in the config file itself? (https://github.com/Eugeny/terminus/wiki/Config-file)

**Comment by birdmanmandbir** [comment] 2019-11-06 14:09
I deleted the config file 'config.yaml', and it seems work. 😊
(https://github.com/Eugeny/terminus/wiki/Config-file)

**Comment by Eugeny** [comment] 2019-11-06 14:10
This is nevertheless an issue for multiple users and configs don't corrupt themselves

**Comment by jaques-sam** [comment] 2019-11-06 14:25
@birdmanmandbir What?! Why is this issue closed? If "delete your config file" seems like *the* solution, I think were on the wrong track of solving issues...

My config file can perfectly be opened so it is __not__ corrupt, still I cannot open the settings:
```yaml
hotkeys:
  shell: {}
  profile: {}
  home: []
  end: []
  close-tab: []
terminal:
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  environment: {}
  profiles:
    - name: Bash
      sessionOptions:
        command: /usr/bin/bash --login -i
        args: []
        env: {}
        cwd: 'C:\Program Files\Git'
  profile: git-bash
  font: MesloLGS NF Regular
  fontSize: 12
  frontend: xterm
  background: theme
  autoOpen: true
  copyOnSelect: true
  bracketedPaste: false
  alwaysUseWorkingDirectory: false
appearance:
  opacity: 0.97
  vibrancy: true
  vibrancyType: blur
  frame: thin
  dock: 'off'
  theme: Standard
  tabsLocation: top
enableWelcomeTab: false
titleControl: {}
```

**Comment by Zebraslive** [comment] 2019-11-06 22:10
maybe add a button on settings page to "force save and check for config syntax errors".

I'm only able to open the settings once then it won't open again until I reopen terminus. 
If you click any other button just after opening terminus it won't let u open settings. So the first thing you have to click is settings. tho u can't save them.... can't save my second ssh connection either. I guess I'll reinstall and try from there.

**Comment by StormYudi** [comment] 2019-11-07 01:23
> maybe add a button on settings page to "force save and check for config syntax errors".
> 
> I'm only able to open the settings once then it won't open again until I reopen terminus.
> If you click any other button just after opening terminus it won't let u open settings. So the first thing you have to click is settings. tho u can't save them.... can't save my second ssh connection either.
> 
> OK. Fixed it by opening config and manually saving once. as soon as you save open terminus and go straight to settings first thing. make your changes and then close and reopen to see effect.
> I kept config open in atom while changing in terminus. all changes saved correctly now and settings window opens normally.

I have the same problem, which has ruined my experience.

**Comment by birdmanmandbir** [comment] 2019-11-09 09:35
@jaques-sam 
Sincerely sorry for that.
You’re right, my config was generated by terminus, but it also corrupted.

**Comment by Eugeny** [comment] 2019-11-26 13:46
Duplicate of #1785

**Closed by Eugeny** 2019-11-26 13:46 UTC
