### ISSUE TITLE
Window not quite fitting screen

### ISSUE THREAD

**Issue by shaqaruden** [Eugeny/terminus#3263] opened 2020-12-28 17:28 UTC
Not sure if you can fix this. I have a 4K main display with a 1080P secondary display. When Terminus is maximized on the 4K display and acrylic background is enabled, I get the edge of the window on the 1080P display. I realize this would not be near as noticeable if the displays were the same resolution.

![image](https://user-images.githubusercontent.com/5414897/103232329-2ab4f380-4908-11eb-9304-a2d9a863e6fe.png)

Version: 1.0.123
Platform: Windows 10 2004

**Comment by shaqaruden** [comment] 2020-12-29 16:53
a little bit info. This only happens when the window is maximized, fitting the window into 1 half of my 4K display does not cause the issue

**Comment by aidenmitchell** [comment] 2021-01-03 20:26
It's an Electron issue, but it should be fixed? https://github.com/electron/electron/pull/25940

**Comment by Eugeny** [comment] 2021-01-03 20:28
Good catch - it's fixed in the Electron 12 beta - I'll upgrade once it's stable

**Comment by Onepamopa** [comment] 2021-01-12 18:39
@Eugeny I don't know if you've upgraded Electron version ... but the blurred edges are still there @ latest terminus version.
Please reopen issue and close once its fixed.

**Comment by Eugeny** [comment] 2021-01-12 20:06
This issue is still open.

**Comment by Eugeny** [comment] 2021-02-13 14:04
We're on Electron 12 now - please reopen if the issue is still there.

**Closed by Eugeny** 2021-02-13 14:04 UTC
Labels: S: Confirmed, T: Bug

**Comment by shaqaruden** [comment] 2021-12-07 06:09
@Eugeny thisbis still an issue in the latest Tabby build. Did you upgrade to Electron 12?

**Comment by shaqaruden** [comment] 2021-12-07 06:09
I still see this issue with the latest version of Tabby

**Comment by shaqaruden** [comment] 2021-12-09 16:42
This is still an issue on 167

![image](https://user-images.githubusercontent.com/5414897/145438739-f48ed75b-0980-4787-b6b6-e4faf5d539d1.png)

**Comment by shaqaruden** [comment] 2021-12-09 16:44
Still an issue on Tabby 167

![image](https://user-images.githubusercontent.com/5414897/145439050-4136f022-46ec-4b4c-9165-572311c26308.png)

**Comment by shaqaruden** [comment] 2021-12-09 17:38
> Still an issue on Tabby 167
> 
> ![image](https://user-images.githubusercontent.com/5414897/145439050-4136f022-46ec-4b4c-9165-572311c26308.png)

@Eugeny
