### ISSUE TITLE
Change the position to dock terminus closed it and it doesn't respond anymore

### ISSUE THREAD

**Issue by franshesco** [Eugeny/terminus#86] opened 2017-07-06 02:01 UTC
Hello,

I would like to inform you that after installing terminus, I was exploring setting. When I have modified the position to dock terminus, it closed. I tried to relaunch it but nothing. Even after uninstalling and reinstalling it.

The OS is centos 7.

Regards.

**Comment by Eugeny** [comment] 2017-07-06 08:15
Duplicate of #9

**Closed by Eugeny** 2017-07-06 08:15 UTC
Labels: duplicate
