### ISSUE TITLE
When I uninstall termius, the right-click menu remains "open path in terminus"

### ISSUE THREAD

**Issue by haocvg** [Eugeny/terminus#1481] opened 2019-09-08 13:16 UTC
When I uninstall termius, the right-click menu remains "open path in terminus"，my system version is 18975.1000

**Comment by nod0n** [comment] 2019-09-26 08:53
For me to!

**Comment by nod0n** [comment] 2019-09-26 08:58
duplicate #1344 ?

**Comment by Eugeny** [comment] 2019-09-26 09:00
Duplicate of #1344

**Closed by Eugeny** 2019-09-26 09:00 UTC
Labels: OS: Windows, S: Confirmed, T: Bug
