### ISSUE TITLE
cant add connection

### ISSUE THREAD

**Issue by windzhu0514** [Eugeny/terminus#1738] opened 2019-11-06 03:31 UTC
`settings`->`Add connection` fill the ssh connection information， then `Save`,connects list does not have the new add one .and dev tools log is 
```
C:\Program Files\Ter…s\core.umd.js:15768 ERROR Error: Uncaught (in promise): YAMLException: unacceptable kind of an object to dump [object Undefined]
YAMLException: unacceptable kind of an object to dump [object Undefined]
    at writeNode (dumper.js:756)
    at writeBlockMapping (dumper.js:634)
    at writeNode (dumper.js:727)
    at writeBlockSequence (dumper.js:521)
    at writeNode (dumper.js:740)
    at writeBlockMapping (dumper.js:634)
    at writeNode (dumper.js:727)
    at writeBlockMapping (dumper.js:634)
    at writeNode (dumper.js:727)
    at dump (dumper.js:817)
    at resolvePromise (C:\Program Files\Ter…js\dist\zone.js:831)
    at C:\Program Files\Ter…js\dist\zone.js:896
    at ZoneDelegate.invokeTask (C:\Program Files\Ter…js\dist\zone.js:423)
    at Object.onInvokeTask (C:\Program Files\Ter…s\core.umd.js:17334)
    at ZoneDelegate.invokeTask (C:\Program Files\Ter…js\dist\zone.js:422)
    at Zone.runTask (C:\Program Files\Ter…js\dist\zone.js:195)
    at drainMicroTaskQueue (C:\Program Files\Ter…js\dist\zone.js:601)
    at ZoneTask.invokeTask [as invoke] (C:\Program Files\Ter…js\dist\zone.js:502)
    at invokeTask (C:\Program Files\Ter…s\dist\zone.js:1744)
    at HTMLButtonElement.globalZoneAwareCallback (C:\Program Files\Ter…s\dist\zone.js:1770)
C:\Program Files\Ter…s\core.umd.js:15768 ERROR Error: Uncaught (in promise): 1
    at resolvePromise (C:\Program Files\Ter…js\dist\zone.js:831)
    at resolvePromise (C:\Program Files\Ter…js\dist\zone.js:788)
    at C:\Program Files\Ter…js\dist\zone.js:892
    at ZoneDelegate.invokeTask (C:\Program Files\Ter…js\dist\zone.js:423)
    at Object.onInvokeTask (C:\Program Files\Ter…s\core.umd.js:17334)
    at ZoneDelegate.invokeTask (C:\Program Files\Ter…js\dist\zone.js:422)
    at Zone.runTask (C:\Program Files\Ter…js\dist\zone.js:195)
    at drainMicroTaskQueue (C:\Program Files\Ter…js\dist\zone.js:601)
    at ZoneTask.invokeTask [as invoke] (C:\Program Files\Ter…js\dist\zone.js:502)
    at invokeTask (C:\Program Files\Ter…s\dist\zone.js:1744)
```

**Comment by Eugeny** [comment] 2019-11-06 11:48
Duplicate of #1665

**Closed by Eugeny** 2019-11-06 11:48 UTC
