### ISSUE TITLE
Feature Request: Detaching Tabs

### ISSUE THREAD

**Issue by lxwulf** [Eugeny/terminus#2050] opened 2020-01-23 13:36 UTC
Sometimes you need both terminals and you wont change everytime the tab so detaching the tab to another would be nice and yah retaching too i think =)

**Comment by Onepamopa** [comment] 2020-01-30 13:47
Good to have!

**Comment by vinguan** [comment] 2020-01-31 13:01
+1. This would be perfect to use with multiple monitors.

**Comment by Eugeny** [comment] 2020-02-06 16:28
Duplicate of #581

**Closed by Eugeny** 2020-02-06 16:28 UTC
Labels: T: Enhancement
