### ISSUE TITLE
Window width bug

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [Eugeny/terminus#230] opened 2017-10-24 08:59 UTC
Version: 1.0.0-alpha.34
Platform: darwin 17.0.0

Infinity (or biggest) window width if chosen "Left" option.
I did not have time to read the name of the parameter in the settings, and after applying the entire left part of the window was far beyond the screen.

Sorry for google translate.

**Comment by sam543381** [comment] 2017-12-06 13:11
Version: 1.0.0-alpha.37
Platform: darwin 15.6.0

Same issue: the window is expanded indefinitively on the right ...
Here's a screenshot [screenshot](https://i.imgur.com/XdEDOw0.png).

Best,
Sam

**Comment by notque** [comment] 2018-02-08 20:08
Same issue, infinitely to the right.

**Comment by Eugeny** [comment] 2018-03-11 19:12
Duplicate of #9

**Closed by Eugeny** 2018-03-11 19:12 UTC

**Comment by csmith14** [comment] 2019-01-25 22:55
This issue is still very present. I have uninstalled and reinstalled, rd /s /q the appdata local folder, everything.
