### ISSUE TITLE
text blank 

### ISSUE THREAD

**Issue by tirthen** [Eugeny/terminus#1055] opened 2019-06-11 16:11 UTC
Version: 1.0.81
Platform: win32 10.0.17763
Plugins: none
after open 2nd tab 1st tab text are disapear and after click somewhere or drag mouse somewhere it will show again

**Comment by IgnusG** [comment] 2019-06-11 16:33
Might be related to https://github.com/Eugeny/terminus/issues/968

**Comment by Eugeny** [comment] 2019-06-11 16:58
Duplicate of #729

**Closed by Eugeny** 2019-06-11 16:58 UTC
