### ISSUE TITLE
Rogue cmd.exe processes and Terminus process not terminating on exit

### ISSUE THREAD

**Issue by benvddriessche** [Eugeny/terminus#625] opened 2019-01-23 14:26 UTC
Since version 67 and up (currently on 69), I frequently encounter rogue cmd.exe processes (nested in the Terminus process) that are continuously consuming a full CPU thread. Manually killing them, "solves" the issue temporarily. Secondly, I occasionally run into the issue where closing the main Terminus window, does not terminate the actual process. Again, killing it manually, solves that.

My main usage of Terminus is basic command line stuff and running Jupyter notebooks. In the latter case, the program is often open for prolonged periods of time, including during sleep/wake cycles of my laptop. It looks like the issues are mainly associated with long Terminus sessions (hours and up). I will continue monitoring to identify more detailed patterns.

Windows 10 1809, fully patched

**Comment by Eugeny** [comment] 2019-01-23 14:38
Likely a duplicate of #609

**Comment by benvddriessche** [comment] 2019-01-23 16:09
I looked for duplicates and missed this one somehow. Thanks!

**Closed** 2019-01-23 16:57 UTC
