### ISSUE TITLE
Cannot connect to some SSH

### ISSUE THREAD

**Issue by Domain** [Eugeny/terminus#430] opened 2018-09-21 10:05 UTC
<pre>
entry.preload.ts:34 Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cannot call write after a stream was destroyed
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cannot call write after a stream was destroyed
    at callFunction (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\electron.asar\browser\rpc-server.js:258:11)
    at EventEmitter.<anonymous> (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\electron.asar\browser\rpc-server.js:360:5)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\electron.asar\browser\api\web-contents.js:293:13)
    at WebContents.emit (events.js:182:13)
    at callFunction (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\electron.asar\browser\rpc-server.js:258:11)
    at EventEmitter.<anonymous> (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\electron.asar\browser\rpc-server.js:360:5)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\electron.asar\browser\api\web-contents.js:293:13)
    at WebContents.emit (events.js:182:13)
    at metaToException (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\electron.asar\renderer\api\remote.js:271:17)
    at Object.exception (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\electron.asar\renderer\api\remote.js:219:30)
    at metaToValue (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\electron.asar\renderer\api\remote.js:223:28)
    at Object.remoteMemberFunction (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\electron.asar\renderer\api\remote.js:123:16)
    at m.write (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\builtin-plugins\terminus-ssh\dist\index.js:313:4325)
    at m.k (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\builtin-plugins\terminus-ssh\dist\index.js:313:672)
    at Object.onceWrapper (events.js:273:13)
    at m.emit (events.js:182:13)
    at m.connect (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\builtin-plugins\terminus-ssh\dist\index.js:313:4483)
    at e.exports (C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\builtin-plugins\terminus-ssh\dist\index.js:313:3258)
process.on.n @ entry.preload.ts:34
emit @ events.js:182
window.onerror @ C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\electron.asar\renderer\init.js:143
C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\builtin-plugins\terminus-core\dist\index.js:190 [hostApp] Unhandled exception: {code: "ENOENT", errno: "ENOENT", path: "C:\util\pagent.exe", spawnargs: Array(1), syscall: "spawn C:\util\pagent.exe"}
doLog @ C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\builtin-plugins\terminus-core\dist\index.js:190
error @ C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\builtin-plugins\terminus-core\dist\index.js:190
n.ipcRenderer.on @ C:\Users\domain\AppData\Local\terminus\app-1.0.0-alpha56\resources\builtin-plugins\terminus-core\dist\index.js:120
emit @ events.js:182
</pre>

Why need C:\util\pagent.exe?

**Comment by Eugeny** [comment] 2018-12-15 13:30
Duplicate of #496

**Closed by Eugeny** 2018-12-15 13:30 UTC
