### ISSUE TITLE
Transparency not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by jorgegarro** [Eugeny/terminus#1833] opened 2019-11-27 15:27 UTC
The transparency is not working on a fresh installation of Ubuntu 18.04. I set the parameter restart Terminus, but nothing changes:

Linux chorch 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nitishingde** [comment] 2020-01-19 17:25
I am also facing the same issue, any updates on this bug?

**Comment by Eugeny** [comment] 2020-01-30 16:26
Duplicate of #832

**Closed by Eugeny** 2020-01-30 16:26 UTC
