### ISSUE TITLE
SSH connection would break after a long time

### ISSUE THREAD

**Issue by RaphaelTFool** [Eugeny/terminus#839] opened 2019-05-24 05:35 UTC
Version: 1.0.77
Platform: win32 6.1.7601
Plugins: altair, clickable-links, quick-cmds, scrollbar, shell-selector, theme-gruvbox, theme-windows10, title-control
is it OK to add a reconnect function??
Thanks

**Comment by Eugeny** [comment] 2019-08-07 13:19
Duplicate of #761

**Closed by Eugeny** 2019-08-07 13:19 UTC
Labels: Plugin: SSH, T: Enhancement
