### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Sabdix** [Eugeny/terminus#739] opened 2019-03-29 23:41 UTC
Version: 1.0.71
Platform: win32 10.0.17763
Plugins: altair, clickable-links, theme-gruvbox, theme-hype, theme-windows10, title-control

When Working with NANO, some of the content freezes, so it looks weird

**Comment by bes-internal** [comment] 2019-04-28 13:38
Did you try to change terminal frontend implementation? Preferences - Apparnce - xterm/hterm

**Comment by Eugeny** [comment] 2019-04-28 15:11
Duplicate of #706

**Closed** 2019-05-24 15:40 UTC
