### ISSUE TITLE
the entire screen is not output via SSH access

### ISSUE THREAD

**Issue by cloud2010** [Eugeny/terminus#1048] opened 2019-06-09 12:55 UTC
Version: 1.0.80
Platform: win32 10.0.18362
Plugins: shell-selector, theme-gruvbox, title-control

SSH accesses the host cannot display properly, the entire screen is not output

**Comment by Eugeny** [comment] 2019-06-09 17:32
Duplicate of #1044

**Closed by Eugeny** 2019-06-09 17:32 UTC
