### ISSUE TITLE
Add cmd line arguments

### ISSUE THREAD

**Issue by ahbrajev** [Eugeny/terminus#2927] opened 2020-08-24 12:15 UTC
Hello,

I find it frustrating that one of the best terminals does not offer us the possibility to add command line arguments for port forwarding and save those to a connection.

Something like: -L 5444:localhost:5432

Thank you

**Comment by Eugeny** [comment] 2020-08-24 12:18
I find it frustrating that everybody thinks that every single SSH client is a thin wrapper around OpenSSH.

Duplicate of #2395

**Closed by Eugeny** 2020-08-24 12:18 UTC
