### ISSUE TITLE
Plus icon for new connection not responding (similar to settings icon)

### ISSUE THREAD

**Issue by jaques-sam** [Eugeny/terminus#1817] opened 2019-11-26 08:24 UTC
Nothing is happening when clicking the + icon on top next to the window.
Same for the settings icon.

Version: 1.0.94
Platform: win32 10.0.17763
Plugins: title-control

**Comment by Eugeny** [comment] 2019-11-26 08:48
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by jaques-sam** [comment] 2019-11-26 08:59
Haha, it's the same as previous issue with the settings button. I cannot reach the settings 👎

**Comment by jaques-sam** [comment] 2019-11-26 09:03
Okay, the key works:

```logs
bundle.js:1587 Caching @angular/animations: 0.38916015625ms
bundle.js:1587 Caching @angular/common: 0.39697265625ms
bundle.js:1587 Caching @angular/compiler: 0.3291015625ms
bundle.js:1587 Caching @angular/core: 0.016845703125ms
bundle.js:1587 Caching @angular/forms: 0.386962890625ms
bundle.js:1587 Caching @angular/platform-browser: 0.4921875ms
bundle.js:1587 Caching @angular/platform-browser-dynamic: 0.012939453125ms
bundle.js:1587 Caching @ng-bootstrap/ng-bootstrap: 0.01708984375ms
bundle.js:1587 Caching ngx-toastr: 0.015869140625ms
bundle.js:1587 Caching rxjs: 0.01416015625ms
bundle.js:1587 Caching rxjs/operators: 0.48681640625ms
bundle.js:1587 Caching rxjs-compat/Subject: 2.43505859375ms
bundle.js:1587 Caching terminus-core: 609.490966796875ms
bundle.js:1587 Caching terminus-settings: 95.376953125ms
bundle.js:1587 Caching terminus-terminal: 683.47216796875ms
bundle.js:1587 Caching zone.js/dist/zone.js: 0.013916015625ms
bundle.js:1494 Starting with plugins: Array(7)
bundle.js:1672 Loading community-color-schemes: C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-community-color-schemes\dist\index.js
bundle.js:1682 Loading community-color-schemes: 9.09130859375ms
bundle.js:1672 Loading core: C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-core\dist\index.js
bundle.js:1682 Loading core: 0.118896484375ms
bundle.js:1672 Loading plugin-manager: C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-plugin-manager\dist\index.js
bundle.js:1682 Loading plugin-manager: 15.287109375ms
bundle.js:1672 Loading settings: C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-settings\dist\index.js
bundle.js:1682 Loading settings: 0.080078125ms
bundle.js:1672 Loading ssh: C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-ssh\dist\index.js
bundle.js:1682 Loading ssh: 316.715087890625ms
bundle.js:1672 Loading terminal: C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-terminal\dist\index.js
bundle.js:1682 Loading terminal: 0.076171875ms
bundle.js:1672 Loading title-control: C:\Users\SAMJA\AppData\Roaming\terminus\plugins\node_modules\terminus-title-control\dist\index.js
bundle.js:1682 Loading title-control: 5.22119140625ms
log.service.ts:56 [hostApp] Window ID: 1
log.service.ts:56 [main] v 1.0.94
C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'LM' of undefined
TypeError: Cannot read property 'LM' of undefined
    at PowerShellCoreShellProvider.eval (powershellCore.ts:26)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js:65)
    at new ZoneAwarePromise (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910)
    at __awaiter (tslib.es6.js:61)
    at PowerShellCoreShellProvider.provide (powershellCore.ts:21)
    at eval (terminal.service.ts:118)
    at Array.map (<anonymous>)
    at TerminalService.eval (terminal.service.ts:118)
    at Generator.next (<anonymous>)
    at resolvePromise (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:831)
    at C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:741
    at rejected (tslib.es6.js:63)
    at ZoneDelegate.invoke (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:391)
    at Object.onInvoke (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17343)
    at ZoneDelegate.invoke (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:390)
    at Zone.run (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:150)
    at C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:889
    at ZoneDelegate.invokeTask (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423)
    at Object.onInvokeTask (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334)
defaultErrorLogger @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768
log.service.ts:56 [updater] No updates
C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR YAMLException
defaultErrorLogger @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768
C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getRegistryKey' of undefined
TypeError: Cannot read property 'getRegistryKey' of undefined
    at ShellIntegrationService.eval (shellIntegration.service.ts:49)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js:65)
    at new ZoneAwarePromise (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910)
    at __awaiter (tslib.es6.js:61)
    at ShellIntegrationService.isInstalled (shellIntegration.service.ts:45)
    at ShellIntegrationService.eval (shellIntegration.service.ts:85)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js:65)
    at new ZoneAwarePromise (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910)
    at resolvePromise (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:831)
    at C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:741
    at rejected (tslib.es6.js:63)
    at ZoneDelegate.invoke (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:391)
    at Object.onInvoke (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17343)
    at ZoneDelegate.invoke (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:390)
    at Zone.run (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:150)
    at C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:889
    at ZoneDelegate.invokeTask (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423)
    at Object.onInvokeTask (C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334)
defaultErrorLogger @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768
C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR YAMLException
defaultErrorLogger @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768
```

**Comment by jaques-sam** [comment] 2019-11-26 09:39
Btw, when clicking on the button, nothing is printed in the console...
When clicking on the settings icon I see:

`C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR YAMLException {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d…7:9)↵    at dump (webpack-internal:///6157:817:7)"}
defaultErrorLogger @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768
ErrorHandler.handleError @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15816
dispatchEvent @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:20580
(anonymous) @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21023
(anonymous) @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:1073
ZoneDelegate.invokeTask @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423
onInvokeTask @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334
ZoneDelegate.invokeTask @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:422
Zone.runTask @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:195
ZoneTask.invokeTask @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:498
invokeTask @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1744
globalZoneAwareCallback @ C:\Users\SAMJA\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1770`

**Comment by Eugeny** [comment] 2019-11-26 13:46
Duplicate of #1785

**Closed by Eugeny** 2019-11-26 13:46 UTC
