### ISSUE TITLE
使用sudo报错

### ISSUE THREAD

**Issue by wwwangzhch** [Eugeny/terminus#1441] opened 2019-09-01 01:18 UTC
使用sudo命令时出现“sudo: 有效用户 ID 不是 0，/usr/bin/sudo 位于一个设置了“nosuid”选项的文件系统或没有 root 权限的 NFS 文件系统中吗？”，但是在系统终端下的sudo命令并没有问题

Version: 1.0.90
Platform: linux 5.0.0-25-generic
Plugins: none

**Comment by Eugeny** [comment] 2019-09-04 09:53
Please translate the ticket to English, thank you.

**Comment by wwwangzhch** [comment] 2019-09-04 10:32
when I use sudo command in terminus, I got  this error"sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?"
but I can use sudo command in Ubuntu's terminal and no error will be reported in this situation.

**Comment by Eugeny** [comment] 2019-09-04 10:45
Duplicate of #960

**Closed by Eugeny** 2019-09-04 10:45 UTC
