### ISSUE TITLE
Feature Request: Full Screen on split terminals

### ISSUE THREAD

**Issue by dmouse** [Eugeny/terminus#829] opened 2019-05-22 04:43 UTC
Hi,
One useful feature in [Terminator](https://terminator-gtk3.readthedocs.io/en/latest/) is the ability to enter on full screen on any split terminal.

Anyone can guide me to implement this feature?

**Comment by Eugeny** [comment] 2019-06-20 12:07
Duplicate of #819

**Closed by Eugeny** 2019-06-20 12:07 UTC
