### ISSUE TITLE
New SSH connections are not saved.

### ISSUE THREAD

**Issue by JensYvanDeCraecker** [Eugeny/terminus#1797] opened 2019-11-23 11:55 UTC
Version: 1.0.92
Platform: win32 10.0.18363
Plugins: theme-gruvbox, theme-hype

**Comment by xwyam** [comment] 2019-11-24 10:16
save with terminus version 1.0.92, windows version windows 10 pro x64 17763.678

**Comment by Eugeny** [comment] 2019-11-26 13:48
Duplicate of #1785

**Closed by Eugeny** 2019-11-26 13:48 UTC
