### ISSUE TITLE
Reporting mouse clicks

### ISSUE THREAD

**Issue by gc1o1** [Eugeny/terminus#2875] opened 2020-08-09 20:45 UTC
Version: 1.0.116
Platform: win32 10.0.18362
Plugins: scrollbar

I connect to a remote server where I run tmux.  Clicking doesn't get reported to tmux.  Same with Vim.  
Instead, terminus highlights text, like it would if I wasn't running an application that listens for mouse events.
I couldn't find any option in the Setting for reporting mouse events.
This prevents me from using terminus, though it otherwise looks very nice.
Thank you.

**Comment by Eugeny** [comment] 2020-08-11 06:45
Duplicate of #290

**Closed by Eugeny** 2020-08-11 06:45 UTC
