### ISSUE TITLE
Blank Screen on Open

### ISSUE THREAD

**Issue by SwingCSS** [Eugeny/terminus#3272] opened 2020-12-31 00:39 UTC
After updating to the latest version of Terminus, there is no data or info being shown. I'm just being presented an empty, gray terminal screen. (On Mac OS X)

**Comment by wjiuxing** [comment] 2020-12-31 04:36
me too. v1.0.123 (1.0.123) on macOS Big Sur 11.1

**Comment by housirvip** [comment] 2020-12-31 06:05
me too. v1.0.123 (1.0.123) macOS 10.15.7

**Comment by eMaitcH75** [comment] 2020-12-31 09:36
It happened to me, too. I have had 3 tabs open. When I opened the fourth one (local terminal), I had the gray screen. Restarting the program does not bring any improvement.

Here is an excerpt from the system log:
The first line is at the "Force Quit Application". 

`
Dec 31 10:34:32 TARDIS com.apple.xpc.launchd[1] (application.org.terminus.13197076.13197082[1140]): Service exited due to SIGTERM | sent by loginwindow[141]
Dec 31 10:34:36 TARDIS com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.org.terminus.13197076.13197082(502)> [957]
Dec 31 10:34:37 TARDIS Terminus Helper (GPU)[1156]: getattrlist failed for /System/Library/Extensions/AppleIntelHD5000GraphicsGLDriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsGLDriver: #2: No such file or directory
Dec 31 10:34:37 TARDIS Terminus Helper (GPU)[1156]: getattrlist failed for /System/Library/Extensions/GeForceGLDriver.bundle/Contents/MacOS/GeForceGLDriver: #2: No such file or directory
Dec 31 10:34:37 TARDIS Terminus Helper (GPU)[1156]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
Dec 31 10:34:37 TARDIS VTDecoderXPCService[1158]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated; set a breakpoint on _dispatch_bug_deprecated to debug
Dec 31 10:34:37 TARDIS VTDecoderXPCService[1158]: DEPRECATED USE in libdispatch client: Changing target queue hierarchy after xpc connection was activated; set a breakpoint on _dispatch_bug_deprecated to debug
Dec 31 10:34:37 TARDIS VTDecoderXPCService[1158]: getattrlist failed for /Library/GPUBundles/AppleIntelHD5000GraphicsVADriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsVADriver: #2: No such file or directory
Dec 31 10:34:37 TARDIS VTDecoderXPCService[1158]: getattrlist failed for /Library/GPUBundles/GeForceVADriver.bundle/Contents/MacOS/GeForceVADriver: #2: No such file or directory
Dec 31 10:34:37 TARDIS VTDecoderXPCService[1158]: getattrlist failed for /Library/GPUBundles/AppleIntelHSWVA.bundle/Contents/MacOS/AppleIntelHSWVA: #2: No such file or directory
Dec 31 10:34:37 TARDIS VTDecoderXPCService[1158]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated; set a breakpoint on _dispatch_bug_deprecated to debug
Dec 31 10:34:37 TARDIS VTDecoderXPCService[1158]: DEPRECATED USE in libdispatch client: Changing target queue hierarchy after xpc connection was activated; set a breakpoint on _dispatch_bug_deprecated to debug
Dec 31 10:34:37 TARDIS VTDecoderXPCService[1158]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated; set a breakpoint on _dispatch_bug_deprecated to debug
Dec 31 10:34:37 TARDIS VTDecoderXPCService[1158]: DEPRECATED USE in libdispatch client: Changing target queue hierarchy after xpc connection was activated; set a breakpoint on _dispatch_bug_deprecated to debug
`

**Comment by tegendraads** [comment] 2020-12-31 13:35
Same here. On 10.15.7. Catalina. Blank screen when starting. Tried to install previous version. Did not help, same thing. 

Deleting /Users/$Username/Library/Application Support/terminus helps but it will remove all your settings as well, putting back config file will bring you back to normal startup, but once you open a tab it is back to the blank screen. This needs an update!

**Comment by SystemFiles** [comment] 2020-12-31 13:56
+1 noticed this immediately after updating to latest on Mac OS Big Sur. I thought it was an issue with the update process (something got corrupted maybe) but I deleted the app and reinstalled from GitHub releases. Did not help at all.

If there is any more information I can provide, I am happy to help! Thanks to all the devs working hard on this <3

**Comment by chadmayfield** [comment] 2021-01-01 06:40
+1 same here on 10.5.7.

**Comment by Eugeny** [comment] 2021-01-01 13:30
Duplicate of #3261

**Closed by Eugeny** 2021-01-01 13:30 UTC
