### ISSUE TITLE
New tab fails every second times

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#591] opened 2019-01-02 00:44 UTC
Version: 1.0.67
Platform: win32 10.0.17763
Plugins: clickable-links, scrollbar

![screenshot](https://user-images.githubusercontent.com/1329716/50577770-85372880-0e83-11e9-8464-a7b15662da20.gif)

**Comment by Nidnogg** [comment] 2019-01-02 23:47
Seeing this as well on Win10 17134.472. It started a while after I configured my initial settings.

**Comment by Eugeny** [comment] 2019-01-03 09:55
Duplicate of #586

**Closed by Eugeny** 2019-01-03 09:55 UTC
