### ISSUE TITLE
"Clear" doesn't always work properly

### ISSUE THREAD

**Issue by M320Trololol** [Eugeny/terminus#623] opened 2019-01-22 10:50 UTC
OS: Windows 10
Shell: Ubuntu 18.04 in WSL

Title is vague af, so some clarification: As you can see in the screenshots below, after exiting a program that takes up the whole terminal (like vim, htop, etc.) the clearing of the screen doesn't always get rid of all remnants.
Even executing another 'clear' doesn't get rid of them.
I assume this is a fault with the renderer, since it does not occur when using the standard WSL terminal.
Another clue pointing to Terminus' renderer is the fact that switching to another tab in Terminus and switching back gets rid of the artifacts.

![image](https://user-images.githubusercontent.com/5568767/51530250-d0b57480-1e3a-11e9-9fe6-32b191edc771.png)

![image](https://user-images.githubusercontent.com/5568767/51530301-eb87e900-1e3a-11e9-811e-1de961b7e8e4.png)

Hope this bug report is useful, if any additional info is needed let me know!

**Comment by Eugeny** [comment] 2019-02-09 22:17
This is very likely a duplicate of #28

**Closed by Eugeny** 2019-02-09 22:17 UTC
