### ISSUE TITLE
Bug add new tab

### ISSUE THREAD

**Issue by ArnaudDoubremelle** [Eugeny/terminus#100] opened 2017-07-07 12:34 UTC
Hello, I am using OS X El Capitan, when i try to open new tab, nothing change. I have just one tab i can't open more. I have test button and hotkey for open but nothing happens.

Thanks

**Comment by Eugeny** [comment] 2017-07-08 11:37
Duplicate of #63 which is already fixed

**Closed** 2017-07-08 11:38 UTC
