### ISSUE TITLE
Attempt to open an admin tab fails. 

### ISSUE THREAD

**Issue by washicjr** [Eugeny/terminus#2834] opened 2020-07-28 23:19 UTC
Every attempt to open a profile with administrator rights fails on Windows 10. It opens and immediately closes.

Terminus Version: 114 
OS: Windows 10 Pro
Version: 2004
OS Build: 19041.388
Window Feature Pack: 120.2202.130.0

**Comment by Eugeny** [comment] 2020-07-29 08:46
Duplicate of #2800

**Closed by Eugeny** 2020-07-29 08:46 UTC
