### ISSUE TITLE
Modify SSH Connections Not Saved

### ISSUE THREAD

**Issue by jwalsh2NU** [Eugeny/terminus#590] opened 2019-01-01 19:27 UTC
Version: 1.0.67
Platform: win32 10.0.17763
Plugins: none

If I modify the Host name in the SSH Connections, it does not get saved.  Changing the name is saved.  Chaning tabs, closing and relaunching the app does not change the behaviour.

**Comment by Eugeny** [comment] 2019-01-01 21:16
Duplicate of #436

**Closed by Eugeny** 2019-01-01 21:16 UTC
