### ISSUE TITLE
Problem detected

### ISSUE THREAD

**Issue by fernandeuz** [Eugeny/terminus#88] opened 2017-07-06 06:27 UTC
Version: 1.0.0-alpha.18
Platform: win32 6.1.7601

Hi.
I recently have installed this application in my Windows 7 PC. 
At start, on the settings, if I press "LEFT" on "Dock the Terminal", application window dessapears.
It continue on the tasks bar (bottom), but although I press over it, it doesn't display. To continue, I must to close application from tasks manager. 
If newly I try to open it, the problem persists.
For hard reset application, I must to drop directory "terminus" in %HOME%\App\Roaming\

**Comment by Eugeny** [comment] 2017-07-06 08:14
Duplicate of #9

**Closed by Eugeny** 2017-07-06 08:14 UTC
Labels: duplicate
