### ISSUE TITLE
Not getting input : (

### ISSUE THREAD

**Issue by techvineyy** [Eugeny/terminus#3403] opened 2021-02-03 13:23 UTC
Version: 1.0.130
Platform: win32 10.0.10240
Plugins: none

Unable to get text input

**Comment by clarkwang** [comment] 2021-02-05 13:36
`1.0.130` is also not usable for me on macOS Catalina (`10.15.7`). This is the first time I try it on macos though `1.0.127` works quite well on Windows 10 (x64). Not sure if it's macos specific or some regression issue after `1.0.127`.

**Comment by clarkwang** [comment] 2021-02-05 14:09
Issue #3399 says it stops working after 1.0.127 on Windows. I downloaded 1.0.127 on macos but it's also unusable for me. It can start but it's very very slow.

**Comment by Eugeny** [comment] 2021-02-06 17:53
@clarkwang can you post your dev console output on macOS? 

@techvineyy it's a duplicate of #3397

**Comment by techvineyy** [comment] 2021-02-07 11:48
#3397 worked for me thanks

**Closed** 2021-02-07 11:48 UTC
