### ISSUE TITLE
emmmm

### ISSUE THREAD

**Issue by 695137400** [Eugeny/terminus#1367] opened 2019-08-09 02:00 UTC
![2019-08-09_095706](https://user-images.githubusercontent.com/13709135/62748721-422ddb00-ba8c-11e9-9dec-50d9f71a7703.png)
emmmm

**Comment by 695137400** [comment] 2019-08-09 02:08
![2019-08-09_100727](https://user-images.githubusercontent.com/13709135/62749074-a1401f80-ba8d-11e9-96b2-4bb4c0e18d9f.png)

**Comment by Eugeny** [comment] 2019-08-09 12:01
Duplicate of https://github.com/Domain/terminus-quick-cmds/pull/11

**Closed by Eugeny** 2019-08-09 12:01 UTC
