### ISSUE TITLE
Few problems using GitBash on Windows 7

### ISSUE THREAD

**Issue by stz184** [Eugeny/terminus#95] opened 2017-07-06 11:36 UTC
Hello!

Sadly, I am forced to use Windows machine for development at work. So, the closest thing to Bash on Windows 7 is GitBash. I always dreamed for tabbed support so I am very happy to find out that Terminus can solve this issue.

I've found the following two problems so far:
- **clear** command make the cursor to jump to the beginning of the screen, but does not clear the console
- **vim** cannot handle the arrow keys. It throws error "E388: Couldn't find definition". It's also impossible to return in insert mode or quit after the error is thrown.

Thanks in advance!

**Comment by equinox** [comment] 2017-07-06 11:43
The "clear" command acting funky on Git Bash has been reported here: https://github.com/Eugeny/terminus/issues/28

**Comment by Eugeny** [comment] 2017-07-08 11:42
Duplicate of #28 and #91

**Closed by Eugeny** 2017-07-08 11:42 UTC
