### ISSUE TITLE
Unable to open any terminal windows in v1.0.94

### ISSUE THREAD

**Issue by chrisponton** [Eugeny/terminus#1818] opened 2019-11-26 08:45 UTC
Version: 1.0.94
Platform: win32 10.0.18362
Plugins: none

New install. Couldnt open any terminal windows via any of the gui. Swiched to version 1.0.92 and all is ok.

**Comment by Eugeny** [comment] 2019-11-26 08:49
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by jk195417** [comment] 2019-11-26 08:59
Same issue here 👋

Version: 1.0.94
Platform: win32 10.0.17763
Plugins: none

![image](https://user-images.githubusercontent.com/15241365/69614416-0be18f00-106e-11ea-8753-6bc9e0051b2e.png)
![image](https://user-images.githubusercontent.com/15241365/69614430-156af700-106e-11ea-9896-ef0633cd972e.png)

**Comment by ZehuanZhang** [comment] 2019-11-26 09:12
i have same problem
this is my console logs @Eugeny 
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'LM' of undefined
TypeError: Cannot read property 'LM' of undefined
    at PowerShellCoreShellProvider.eval (powershellCore.ts:26)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js:65)
    at new ZoneAwarePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910)
    at __awaiter (tslib.es6.js:61)
    at PowerShellCoreShellProvider.provide (powershellCore.ts:21)
    at eval (terminal.service.ts:118)
    at Array.map (<anonymous>)
    at TerminalService.eval (terminal.service.ts:118)
    at Generator.next (<anonymous>)
    at resolvePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:831)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:741
    at rejected (tslib.es6.js:63)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:391)
    at Object.onInvoke (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17343)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:390)
    at Zone.run (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:150)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:889
    at ZoneDelegate.invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423)
    at Object.onInvokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334)

**Comment by kachunkachunk** [comment] 2019-11-26 09:33
Oops, me as well. I thought I messed something up in my troubleshooting today, heh.

Under Shell, profiles will be empty/blank with no selections available in the dropdown (like clink, powershell, etc).

**Comment by Jangmingjin** [comment] 2019-11-26 09:36
I also has same issue in windows

**Comment by Eugeny** [comment] 2019-11-26 09:57
Duplicate of #1822

**Closed by Eugeny** 2019-11-26 09:57 UTC
