### ISSUE TITLE
Switching window black screen

### ISSUE THREAD

**Issue by swimmingchar** [Eugeny/terminus#1160] opened 2019-07-03 07:02 UTC
Whenever I switch window 2 and return to window 1, the whole screen is black. When I press the Enter key, the font will be visible.

**Comment by wutz** [comment] 2019-07-03 07:29
+1

**Comment by node-lux** [comment] 2019-07-03 07:35
yep, and history log will be disappear

**Comment by IgnusG** [comment] 2019-07-03 14:28
Seems like a duplicate of https://github.com/Eugeny/terminus/issues/729

**Comment by Eugeny** [comment] 2019-07-03 14:33
Duplicate of #729

**Closed by Eugeny** 2019-07-03 14:33 UTC
