### ISSUE TITLE
[Bug Report] incorrect color scheme after getting out of GNU/screen

### ISSUE THREAD

**Issue by Alex4386** [Eugeny/terminus#779] opened 2019-04-23 04:04 UTC
**Shell:** bash
**local Platform:** macOS 10.14.4 (Mojave)
**Steps to reproduce:**
1. create a screen with `screen -S screenName`
2. terminate screen with `exit`
3. The color schemes are strange.

Same Applies to Ubuntu 18.04.2 LTS with Secure Shell Connection.

**Comment by Alex4386** [comment] 2019-04-23 04:04
Providing Image for troubleshooting:
![image](https://user-images.githubusercontent.com/27724108/56553137-5d053e00-65c8-11e9-8711-4bfd7e810dad.png)

**Comment by Alex4386** [comment] 2019-04-28 15:51
**Update:** Provided Bug is not caused in Build 73, Which was the last build before the update.
![image](https://user-images.githubusercontent.com/27724108/56866825-e8dbf780-6a18-11e9-8913-3a8d7207c4a6.png)  

Likely Update to Build 75 caused this issue.

**Comment by Alex4386** [comment] 2019-04-29 16:30
**Update:** Downgrading Xterm to 1.12.2 fixed this issue.  
This bug is related to xterm, Closing issue for now.

**Comment by Tyriar** [comment] 2019-04-29 18:22
@Eugeny @Alex4386 were you on xterm@3.13.0-beta1 when this repro'd?

**Comment by Tyriar** [comment] 2019-04-29 18:22
Oh nevermind, I saw beta2 in the xterm report. Thanks 😃

**Comment by Eugeny** [comment] 2019-04-29 18:39
I'll keep this open - otherwise I'll forget to recheck this when 3.13 is released

**Comment by Tyriar** [comment] 2019-04-29 18:50
@Eugeny thanks trying out the beta build, the reports are extremely helpful 🙂

**Comment by Eugeny** [comment] 2019-04-29 18:57
@Tyriar you're welcome, can't wait for the webgl renderer to get released! :) I'm going to roll back to 3.12 in the next release though, the Unicode char coloring bug is too much for the users.

**Comment by Tyriar** [comment] 2019-04-29 19:01
@Eugeny understandable.

Yeah I'm having trouble finding time to finish the webgl renderer off, the problem is it has quite a lot of pre-requisites due to the decision not to include it in core (primarily https://github.com/xtermjs/xterm.js/issues/2005, https://github.com/xtermjs/xterm.js/issues/1128). It also just broke because of the UTF32 changes and will need some a little updating to support true color (:tada:).

**Comment by Alex4386** [comment] 2019-04-30 06:29
@Tyriar 
Yes, It was reproduced in xterm 3.13.0-beta1 (which is this repo does in package.json),  
Since It was not up-to-date, I manually updated to 3.13.0-beta2 and checked, and since the bugs are reproduced, I found out this was xterm issue, and created issue at xtermjs/xterm.js#2030

**Comment by jerch** [comment] 2019-05-05 20:09
Any idea how this can be repro'ed with xterm.js demo? Note that for me the prompt correctly changes colors for screen, also reliable for detaching/reattaching (from some greenish thing to blue/red prompt).

**Comment by Eugeny** [comment] 2020-02-29 14:59
Has been fixed in xterm since.

**Closed by Eugeny** 2020-02-29 14:59 UTC
Labels: S: Confirmed, T: Bug
