### ISSUE TITLE
When you start terminal first time with xterm (any)

### ISSUE THREAD

**Issue by AlphaS-code** [Eugeny/terminus#2501] opened 2020-04-30 06:29 UTC
![image](https://user-images.githubusercontent.com/26285012/80679224-20b2ca80-8ac5-11ea-9e61-f2e2d1b67d25.png)

**Comment by Eugeny** [comment] 2020-05-02 12:26
Duplicate of #2404

**Closed by Eugeny** 2020-05-02 12:26 UTC
