### ISSUE TITLE
"exit" doesn't exit.

### ISSUE THREAD

**Issue by Hackmastr** [Eugeny/terminus#94] opened 2017-07-06 11:30 UTC
Version: 1.0.0-alpha.18
Platform: win32 6.1.7601

Hello,

if I type exit, i'm expecting Terminus to actually exit, not do this:

![image](https://user-images.githubusercontent.com/9281515/27909058-2bad4fc4-624f-11e7-85cf-bd2f7cf1d20a.png)

It just stays like that, i must close the tab manually.

**Comment by Calinou** [comment] 2017-07-06 13:01
I can confirm this on 1.0.0-alpha.18 on Windows 10 Creators Update; once you type `exit`, input has no effect whatsoever and the tab must be closed manually.

**Comment by jmdf** [comment] 2017-07-06 14:33
Appears to be the same as #84 
I have the same issue while running Bash on Windows, on Windows 10.

**Comment by Eugeny** [comment] 2017-07-08 11:45
Duplicate of #84

**Closed by Eugeny** 2017-07-08 11:45 UTC
