### ISSUE TITLE
Cutting CPU Speed while Running

### ISSUE THREAD

**Issue by valsamis-d** [Eugeny/terminus#2080] opened 2020-01-31 18:18 UTC
Hello,

First off, this is very good. I found out about it a few days ago and started using it immediately in my Desktop. So far, flawlessly.

However, whenever I execute in my laptop for some reason the CPU speed is cut to 0.78 GHz (!) when its base speed is 2.59 GHz. After terminating Terminus CPU speed goes back to 2.59+ (even 3.26 GHz) GHz.

See below:

![While_Terminus_is_Running](https://user-images.githubusercontent.com/17590539/73563726-bc04b700-4466-11ea-8d82-e7a01d8038ae.jpg)

![Before_and_After_Terminating](https://user-images.githubusercontent.com/17590539/73563742-c32bc500-4466-11ea-84e6-64dc8e4a8a3c.jpg)

Any ideas why this might be happening?

Thank you
Dimitrios

**Comment by Eugeny** [comment] 2020-01-31 18:32
When you quit Terminus, there's a CPU usage spike, which disables CPU throttling and/or moving it back into the C0 state. You should see CPU clock drop down whenever nothing is happening on it.

**Comment by valsamis-d** [comment] 2020-01-31 19:03
@Eugeny thanks for getting back to me, but I'm afraid I didn't explain the issues clearly.

The problem is not that I observe CPU spikes but that for some reason the speed capacity of the CPU is lowered 0.78 GHz for a long at Terminus is open/executing. The end result is that my laptop is practically non-usable as everything is extremely slow, even typing in Terminus itself.

By the time I quit Terminus CPU is running at full speed.

Dimitrios

**Comment by Eugeny** [comment] 2020-02-05 11:32
Unfortunately there's nothing I can do at the moment. I'm unable to reproduce this on any of my systems and there are no Electron bugs mentioning this.

**Closed by Eugeny** 2020-02-05 11:32 UTC
