### ISSUE TITLE
rz -b does't work, sz works well

### ISSUE THREAD

**Issue by wengxk** [Eugeny/terminus#2375] opened 2020-04-10 11:44 UTC
Version: 1.0.105
Platform: win32 10.0.18363
Plugins: none

![feedback 2020-04-10 193934](https://user-images.githubusercontent.com/16595800/78988420-71d53b80-7b63-11ea-81f9-4ccf6c634d52.png)

**Comment by Eugeny** [comment] 2020-04-14 07:22
Duplicate of #2352

**Closed by Eugeny** 2020-04-14 07:22 UTC
