### ISSUE TITLE
tmux seems to don't work

### ISSUE THREAD

**Issue by ShiroUsagi-san** [Eugeny/terminus#245] opened 2017-11-24 19:16 UTC
# Tmux not working?
Hey there, 

I've recently move to terminus on an arch linux. I've tried to launch it with screen, it's working without any issues. But, then I've tried to launch it with Tmux... And I've got an error in the devtool:
```Js
ERROR Error: Uncaught (in promise): [object Object]
    at resolvePromise (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:770)
    at /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:696
    at rejected (css-base.js:75)
    at ZoneDelegate.invoke (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:391)
    at Object.onInvoke (ng_zone.ts:296)
    at ZoneDelegate.invoke (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:390)
    at Zone.run (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:141)
    at /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:818
    at ZoneDelegate.invokeTask (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:424)
    at Object.onInvokeTask (ng_zone.ts:288)
```
but, I don't know how to fix this error. 

So i opened this issue,
thanks for reading.

**Comment by Eugeny** [comment] 2018-03-11 19:16
Duplicate of #300

**Closed by Eugeny** 2018-03-11 19:16 UTC
Labels: OS: Linux, T: Bug
