### ISSUE TITLE
Can't open a shell

### ISSUE THREAD

**Issue by OpaNurgle** [Eugeny/terminus#3416] opened 2021-02-06 00:06 UTC
Version: 1.0.130
Platform: win32 10.0.19042
Plugins: none

i just turn on my PC and when i try to open a shell its close at the same time. Its only works correctly with powerShell

This is the profiles which I have
![image](https://user-images.githubusercontent.com/58249237/107101394-75832e80-6817-11eb-8a7d-4702af9c8f45.png)

**Comment by Eugeny** [comment] 2021-02-06 16:45
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by OpaNurgle** [comment] 2021-02-06 18:36
Hey, ty for the answer, here are the logs

electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
electron/js2c/renderer_init.js:93 Unable to load preload script: C:\Users\alexa\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js
(anonymous) @ electron/js2c/renderer_init.js:93
electron/js2c/renderer_init.js:93 TypeError: electron_1.crashReporter.start is not a function
    at RendererBackend._installNativeHandler (C:\Users\alexa\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:8838)
    at new RendererBackend (C:\Users\alexa\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:8774)
    at RendererClient.BaseClient (C:\Users\alexa\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:5800)
    at new RendererClient (C:\Users\alexa\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:8890)
    at Module.initAndBind (C:\Users\alexa\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:6606)
    at init (C:\Users\alexa\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:8980)
    at Object.5828 (C:\Users\alexa\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:15356)
    at __webpack_require__ (C:\Users\alexa\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:15882)
    at C:\Users\alexa\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:15942
    at Object.<anonymous> (C:\Users\alexa\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:15943)
(anonymous) @ electron/js2c/renderer_init.js:93
bundle.js:1548 Caching @angular/animations: 0.080810546875 ms
bundle.js:1548 Caching @angular/common: 0.051025390625 ms
bundle.js:1548 Caching @angular/compiler: 0.06787109375 ms
bundle.js:1548 Caching @angular/core: 0.0048828125 ms
bundle.js:1548 Caching @angular/forms: 0.072021484375 ms
bundle.js:1548 Caching @angular/platform-browser: 0.02197265625 ms
bundle.js:1548 Caching @angular/platform-browser-dynamic: 0.0048828125 ms
bundle.js:1548 Caching @ng-bootstrap/ng-bootstrap: 0.004150390625 ms
bundle.js:1548 Caching ngx-toastr: 0.004150390625 ms
bundle.js:1548 Caching rxjs: 0.00390625 ms
bundle.js:1548 Caching rxjs/operators: 0.06201171875 ms
bundle.js:1548 Caching terminus-core: 257.727294921875 ms
bundle.js:1548 Caching terminus-settings: 77.09423828125 ms
bundle.js:1548 Caching terminus-terminal: 329.882080078125 ms
bundle.js:1548 Caching zone.js/dist/zone.js: 0.016845703125 ms
bundle.js:1459 Starting with plugins: Array(7)
bundle.js:1633 Loading community-color-schemes: C:\Users\alexa\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-community-color-schemes\dist\index.js
bundle.js:1643 Loading community-color-schemes: 37.87109375 ms
bundle.js:1633 Loading core: C:\Users\alexa\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-core\dist\index.js
bundle.js:1643 Loading core: 0.181884765625 ms
bundle.js:1633 Loading plugin-manager: C:\Users\alexa\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-plugin-manager\dist\index.js
bundle.js:1643 Loading plugin-manager: 58.53515625 ms
bundle.js:1633 Loading serial: C:\Users\alexa\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-serial\dist\index.js
bundle.js:1643 Loading serial: 69.055908203125 ms
bundle.js:1633 Loading settings: C:\Users\alexa\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-settings\dist\index.js
bundle.js:1643 Loading settings: 0.0810546875 ms
bundle.js:1633 Loading ssh: C:\Users\alexa\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-ssh\dist\index.js
bundle.js:1643 Loading ssh: 391.56396484375 ms
bundle.js:1633 Loading terminal: C:\Users\alexa\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-terminal\dist\index.js
bundle.js:1643 Loading terminal: 0.1279296875 ms
C:\Users\alexa\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:5385 [hostApp] Window ID: 1

**Comment by Eugeny** [comment] 2021-02-13 14:03
Duplicate of #3397

**Closed by Eugeny** 2021-02-13 14:03 UTC
