### ISSUE TITLE
Can't get to parameters

### ISSUE THREAD

**Issue by HollyFredD** [Eugeny/terminus#1729] opened 2019-11-02 14:39 UTC
Version: 1.0.92
Platform: win32 10.0.18362
Plugins: none

Parameters menu can't be accessed. Either from the top right icon or from the middle screen box. I have to close the app, launch it again and it then sometimes works.

**Comment by Eugeny** [comment] 2019-11-26 14:05
Duplicate of #1785

**Closed by Eugeny** 2019-11-26 14:05 UTC
