### ISSUE TITLE
Terminus loads, but splash screen does not

### ISSUE THREAD

**Issue by crstauf** [Eugeny/terminus#3269] opened 2020-12-29 17:38 UTC
When opening Terminus, I see the loading screen, but the options (ex: create terminal) do not appear; it's just a gray window (see screenshot).

Terminus 1.0.123
macOS Big Sur 11.1

<img width="1080" alt="Screen Shot 2020-12-29 at 12 37 46 PM" src="https://user-images.githubusercontent.com/4573033/103302935-c90d8b80-49d2-11eb-88c2-72e4aa514422.png">

**Comment by wielsma** [comment] 2020-12-29 19:50
Same problem here. Unable to open new window or tab, nor can I access the settings.

MacOS: Big Sur 1.11
MacBook Air (M1, 2020)

**Comment by crstauf** [comment] 2020-12-29 20:47
To add context, I'm experiencing the issue on iMac Pro 2017 (read: not M1).

**Comment by omribenish** [comment] 2020-12-30 11:07
same here

**Comment by dustlrdk** [comment] 2020-12-30 11:50
Same here with Macbook pro(13 inch, 2018, Big Sur).

**Comment by matias-miranda** [comment] 2020-12-30 15:12
same here, if it helps: Macbook Pro 2019. BigSur 11.1

**Comment by Eugeny** [comment] 2020-12-30 18:48
Duplicate of #3261

**Closed by Eugeny** 2020-12-30 18:48 UTC
