### ISSUE TITLE
🤗 Feature Request: Detach window

### ISSUE THREAD

**Issue by ruslanguns** [Eugeny/terminus#1643] opened 2019-10-17 21:58 UTC
I think it would be nice to have the availability to take a tab and separate into a separate windows when needed. Since it would be perfect when it is required to see the logs or executions of what happens in different windows in the work area.

Currently I must go (in Windows) to the taskbar and open a new window of Terminus to have independent windows and I think it could be made easier, precisely for when you want to take the same session from the terminal at the point where you are without interrupting it or having to start a new session.

* Detach window on Right Click
> ![image](https://user-images.githubusercontent.com/19806968/67050531-a3c79100-f130-11e9-81a4-097f31a0bf6c.png)

* Detach window on Drag and Drop
> ![image](https://user-images.githubusercontent.com/19806968/67050802-53046800-f131-11e9-8a0e-5ad1beb5f58e.png)

**Comment by cburj** [comment] 2019-10-23 08:08
+1 - Would love to see this.

**Comment by Eugeny** [comment] 2020-02-06 16:28
Duplicate of #581

**Closed by Eugeny** 2020-02-06 16:28 UTC
Labels: T: Enhancement
