### ISSUE TITLE
Error: Can't open display: (null)

### ISSUE THREAD

**Issue by infinitydon** [Eugeny/terminus#843] opened 2019-05-24 08:52 UTC
Hi,

I am using terminus to SSH into a Linux VM, so I tried to paste some texts from my Win 10 clipboard into the SSH session using pbpaste but I got the following error:

**Error: Can't open display: (null)**

Am not sure if this has to do with some settings or should be a feature request.

Also echo $DISPLAY shows nothing:

```
$ echo $DISPLAY

```

**Comment by Eugeny** [comment] 2019-05-24 08:53
I think the error is missing in your ticket.

**Comment by infinitydon** [comment] 2019-05-24 08:57
I have updated the post now.

**Comment by Eugeny** [comment] 2019-05-24 08:58
Duplicate of #630

**Comment by Eugeny** [comment] 2019-05-24 08:58
Terminus doesn't support X11 forwarding at this moment

**Closed by Eugeny** 2019-05-24 08:58 UTC
