### ISSUE TITLE
When open new terminal, cursor always at the center left of window

### ISSUE THREAD

**Issue by ansidev** [Eugeny/terminus#242] opened 2017-11-22 03:21 UTC
<img width="1680" alt="terminus" src="https://user-images.githubusercontent.com/6688235/33108464-d0518d4c-cf6e-11e7-8d2e-bfbfe8439251.png">

**Comment by Eugeny** [comment] 2017-11-27 20:23
Duplicate of #11

**Closed by Eugeny** 2017-11-27 20:23 UTC
