### ISSUE TITLE
Hotkey Jump to previous/next word doesn't works

### ISSUE THREAD

**Issue by ElieNamias** [Eugeny/terminus#2841] opened 2020-07-29 11:36 UTC
Version: 1.0.114
Platform: win32 10.0.18363
Plugins: altair, clickable-links, relaxed-theme, theme-hype, theme-windows10

That shortcut display the letter b instead of jump to the previous word 
![image](https://user-images.githubusercontent.com/5574782/88795552-82f09980-d1a0-11ea-95eb-251f66e3a79c.png)

**Comment by gaston-senac** [comment] 2020-07-29 22:04
Duplicate of #2739

**Closed** 2020-07-30 06:57 UTC
