### ISSUE TITLE
Font issue, let's call that, some blank white boxes letters.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Eugeny/terminus#700] opened 2019-03-02 15:39 UTC
![](https://i.boring.host/RJOxozH.png)
As you can see, This does put a little issue when trying to use `nano` to edit some text files.
I'm on Microsoft Windows 10 Build 18305.1003 and using the Dank mono font.

**Comment by Eugeny** [comment] 2019-03-03 12:44
Duplicate of #610

**Closed by Eugeny** 2019-03-03 12:44 UTC
