### ISSUE TITLE
[Feature Request] Immediately show console instead of start window

### ISSUE THREAD

**Issue by Simsch** [Eugeny/terminus#200] opened 2017-09-13 18:45 UTC
It would be good to have an option (toggle) which can be activated in order to show the console window right after the start.

(btw. keep up the good work! This is the console I always wanted to have on windows where other console emulators look horrible)

**Comment by Eugeny** [comment] 2017-09-29 07:45
Duplicate of #107

**Closed by Eugeny** 2017-09-29 07:45 UTC
Labels: S: Triaged, T: Enhancement
