### ISSUE TITLE
terminus shield the hotkey(ctrl+@)(ctrl+v)

### ISSUE THREAD

**Issue by github-pengbin** [Eugeny/terminus#723] opened 2019-03-17 09:18 UTC
I think the problem is that terminus shield the hotkey(ctrl+*). when you use the vim editor (ctrl+v)can't enter block visual mode, and when you use the zssh (ctrl+@) can't work . this issue like #718 and #713

**Comment by Eugeny** [comment] 2019-03-17 10:51
Duplicate of #718 and #713

**Closed by Eugeny** 2019-03-17 10:51 UTC
