### ISSUE TITLE
Error: Cannot find module 'npm' under Mac OS v1.0.79

### ISSUE THREAD

**Issue by CreativeBulma** [Eugeny/terminus#1038] opened 2019-06-07 08:11 UTC
I just installed last version (1.0.79) and I get the following error message (NPM is well installed and npm command is working in termnial) when trying to install plugin.

<code>
Error: Cannot find module 'npm'
Require stack:
- /Applications/Terminus.app/Contents/Resources/app.asar/dist/index.html
</code>

**Comment by Novezeil** [comment] 2019-06-07 08:29
Same - but on both Windows 10 and OSX.

**Comment by Eugeny** [comment] 2019-06-07 08:42
Duplicate of #714

**Closed by Eugeny** 2019-06-07 08:42 UTC
Labels: OS: macOS, T: Bug
