### ISSUE TITLE
Blur on screens edge in multi monitors

### ISSUE THREAD

**Issue by Onepamopa** [Eugeny/terminus#3316] opened 2021-01-09 22:10 UTC
Hello,
I'm using 3 monitors, Terminus is on the "middle" monitor.

For some reason when Terminus is maximized and active (focused) - I see blur ~ 5 mm on the left and right screens edges from top to bottom.

Please check this.

**Comment by Eugeny** [comment] 2021-01-10 13:01
Duplicate of #3263

**Closed by Eugeny** 2021-01-10 13:01 UTC
