### ISSUE TITLE
Moving a window is sluggish

### ISSUE THREAD

**Issue by xRosaceae** [Eugeny/terminus#2816] opened 2020-07-24 17:41 UTC
Version: 1.0.113
Platform: win32 10.0.19041
Plugins: altair, relaxed-theme, scrollbar

When I try to move a window with cursor it has some delay and takes some time until it react for any movement at all.

**Comment by swichers** [comment] 2020-07-26 03:17
Can confirm this. After updating to the 19041 windows release the Terminus window has a significant delay while moving it around. It lags several seconds behind the cursor, and will continue moving even if you let go of the window.

I tracked it down to the Fluent background setting. Changing to Blur lets the application work as normal. Disabling the acrylic background also has it work normal.

**Comment by Eugeny** [comment] 2020-07-27 14:15
Duplicate of #949

**Closed by Eugeny** 2020-07-27 14:15 UTC
