### ISSUE TITLE
Typing '@' doesn't work on German keyboard layout (Windows)

### ISSUE THREAD

**Issue by PascalTemel** [Eugeny/terminus#104] opened 2017-07-08 08:45 UTC
Not only the @ symbol is affected, but most symbols that are produced using the AltGr key, like ~ and €.
The symbol '{' works (AltGr + 7), however, '}' doesn't (AltGr + 9). Until this is fixed Terminus is basically unusable for German users.
Doesn't matter which shell is used.

**Comment by Eugeny** [comment] 2017-07-08 11:39
Duplicate of #17

**Closed by Eugeny** 2017-07-08 11:39 UTC
