### ISSUE TITLE
Input broken after upgrading to Alpha 75

### ISSUE THREAD

**Issue by glen-84** [Eugeny/terminus#777] opened 2019-04-22 10:43 UTC
If I type `tslint -p`, I get `tslint - `.

![image](https://user-images.githubusercontent.com/261509/56496941-ce2aef80-64fb-11e9-8b96-06e150698de8.png)

**Shell:** Git-Bash
**ConPTY:** Disabled.
**OS:** Windows 10 Home (Version 10.0.17763 Build 17763)

**Comment by glen-84** [comment] 2019-04-22 10:48
The prompt is also broken:

![image](https://user-images.githubusercontent.com/261509/56497159-c0299e80-64fc-11e9-8772-17775a380590.png)

That should read `Glen@Glen-PC`.

**Comment by bes-internal** [comment] 2019-04-28 12:05
1. `Home`  and `End` hotkeys do not work in linux console (ssh). Both xterm/hterm. If reasign home and end button works.
2. PageUp and PageDown produce "~" in linux promt but works in console editor like nano
3. Sometimes copy and paste by third mouse button insert 0~<copied text>1~ with terminus alert "Illegal sequence"

**Comment by Eugeny** [comment] 2019-04-28 13:07
Duplicate of #778

**Closed by Eugeny** 2019-04-28 13:07 UTC
