### ISSUE TITLE
Uninstaller does not remove 'Open Terminus Here'

### ISSUE THREAD

**Issue by winetree** [Eugeny/terminus#812] opened 2019-05-12 01:58 UTC
Context menu still exist even when i uninstalled this app,
So i had to open my registry editor and deleted registry manually.
please consider uninstaller feature in next release.
Sorry for my bad english, and thank you for your work.

**Comment by glen-84** [comment] 2019-05-16 08:23
Duplicate of #682.

**Closed** 2019-05-16 08:29 UTC
