### ISSUE TITLE
Huge leak when using Clink shell

### ISSUE THREAD

**Issue by NatoBoram** [Eugeny/terminus#636] opened 2019-01-30 04:28 UTC
```yaml
OS: Windows 10 Pro x86_64
Host: System manufacturer
Kernel: 2.11.2(0.329/5/3)
Uptime: 1 hour, 33 mins
Shell: bash 4.4.23
Resolution: 1920x1080
DE: Aero
WM: Explorer
WM Theme: Roamed
CPU: Intel i5-3570K (4) @ 3.468GHz
GPU: NVIDIA GeForce GTX 660 Ti
Memory: 5044MiB / 8135MiB
```

**Bug :** Terminated `clink` sessions stay in memory and eat up CPU power like crazy

**How to reproduce :**

1. Have `clink` as your Terminus shell
2. Start a bunch of sessions and `exit` or close them
3. After a while, close normally Terminus
4. Check the Task Manager

At this point, normally, Terminus is terminated and the `clink` shells are gone. In practice, `clink` shells are now orphans and mining 100% CPU resources for no reason.

This does not happen with `cmd`, `powershell` nor `bash`.

Anyone using `clink` is advised to change shell then reboot Windows.

**Comment by sectorogo** [comment] 2019-02-04 09:07
I can confirm that issue. It happens the same on my computer running Windows 10 Pro 1809 x64.

**Comment by Eugeny** [comment] 2019-02-09 21:26
Duplicate of #609

**Closed by Eugeny** 2019-02-09 21:26 UTC

**Comment by Riwaha** [comment] 2019-02-28 21:08
There appears to still be an issue related to this perhaps.
When closing via `exit` cmd.exe and conhost.exe exit cleanly, however if I click the X, both cmd.exe and conhost.exe stay running in the background.
