### ISSUE TITLE
Strange but, git commands like pull/push stop working since 115

### ISSUE THREAD

**Issue by leocreo** [Eugeny/terminus#2872] opened 2020-08-09 03:40 UTC
Version: 1.0.116
Platform: win32 10.0.19042
Plugins: relaxed-theme

**Comment by Sendoo** [comment] 2020-08-10 07:57
I have the same thing, rolled back to version 114

**Comment by leocreo** [comment] 2020-08-10 11:59
Yes i did the same, but Terminus updates automatically in background and then comes 116 again!

**Comment by Sendoo** [comment] 2020-08-10 12:24
> Yes i did the same, but Terminus updates automatically in background and then comes 116 again!

In the settings, you can turn off automatic updates.

**Comment by leocreo** [comment] 2020-08-10 12:49
You are right, nice tip!! Thanks!! 
I will wait for a full solution to the issue then.

**Comment by Eugeny** [comment] 2020-08-12 19:32
Duplicate of #2868

**Closed by Eugeny** 2020-08-12 19:32 UTC
