### ISSUE TITLE
SSH session and function/keypad keys are not working.

### ISSUE THREAD

**Issue by marcinbojko** [Eugeny/terminus#838] opened 2019-05-23 05:48 UTC
Version: 1.0.77
Platform: linux 4.18.0-20-generic
Plugins: altair, clickable-links, quick-cmds, save-output, scrollbar, shell-selector, theme-gruvbox, title-control

When connected via ssh (xterm/hterm) alike, END/HOME/PageUp/PageDown seems to not working properly.

**Comment by quoidautre** [comment] 2019-05-23 10:08
Hi,
Same issue for me, only in SSH. In "default' command line, it's working.

F.

**Comment by jbelien** [comment] 2019-05-24 07:42
I have the same issue.
This is a duplicate of #787 though :)

**Comment by Eugeny** [comment] 2019-05-24 08:54
Duplicate of #787

**Closed by Eugeny** 2019-05-24 08:54 UTC
