### ISSUE TITLE
Starting up a cmd tab freezes the window for a while

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#83] opened 2017-07-06 00:22 UTC
![terminus-cmd](https://user-images.githubusercontent.com/1329716/27890086-0585fc80-6234-11e7-9078-51b99ec64773.gif)

The screenshot includes key strokes.

The whole windows is frozen for 10-20 seconds, i.e. can't open settings, can't open new tabs, can't type. The typed characters will appear when the frozen period is over, though. New tabs will show, too, if you tried to open a new tab during the period.

The same does not happen when I use powershell. (I mainly use powershell so it's not critical to me, just want to report it since I noticed it)

**Comment by princemaple** [comment] 2017-07-06 00:32
There's a similar issue when I use powershell though, not sure if related. When running npm install / docker build, the window freezes for a while too, even though the output is not large at all. My docker build output is only 30 lines. Also happens when I ssh into other machines, the text above the prompt shows up immediately, but the prompt doesn't show for a while, during which the windows is frozen as well.

**Comment by princemaple** [comment] 2017-07-06 22:14
Ah git diff also freezes it, even though it's only one page long and finishes instantly.

**Comment by equinox** [comment] 2017-07-09 10:35
I also experience this. I'm using Windows 10.

**Comment by princemaple** [comment] 2017-07-12 02:17
@Eugeny I got a profile recorded

![image](https://user-images.githubusercontent.com/1329716/28098850-f98e14cc-66fb-11e7-957f-8c6b5e63d143.png)

For a good 22s period it's frozen in this stack.

**Comment by princemaple** [comment] 2017-07-12 02:22
![image](https://user-images.githubusercontent.com/1329716/28098970-ca11eed4-66fc-11e7-8648-0b45d50be753.png)

**Comment by Eugeny** [comment] 2017-07-12 18:30
So this is caused by the Clickable Links plugin. As a quick workaround, uninstall it. Meanwhile, I'll try to figure out the reason for the freeze.

**Comment by princemaple** [comment] 2017-07-12 23:49
@Eugeny aha it's indeed it. I went straight to plugins and installed clickable links plugin when I first installed terminus, and I never knew it actually works without. Thanks for looking into this.

**Comment by princemaple** [comment] 2018-08-27 08:04
Hmm has this been solved in clickable links? 

Just tested, the window is no longer frozen, but clickable links doesn't seem to work at all.

**Comment by Eugeny** [comment] 2018-10-07 12:33
Now fixed

**Closed by Eugeny** 2018-10-07 12:33 UTC

**Comment by princemaple** [comment] 2018-10-08 05:50
@Eugeny will you make a release of clickable-links soon?

**Comment by Eugeny** [comment] 2018-10-08 06:46
@princemaple done!

**Comment by princemaple** [comment] 2018-10-08 06:49
Don't see an update on NPM just yet. I'll try again in a few hours. Thanks for the notice anyway!
