### ISSUE TITLE
Display is very laggy

### ISSUE THREAD

**Issue by mkaraki** [Eugeny/terminus#1728] opened 2019-11-02 14:27 UTC
When I use Terminus, it's so very laggy when I input text and output text.
I've tried another terminal emulator(Cmder, Hyper and Windows Default Console) but there are no lag like that.
When I use hterm, more better latency but it's still laggy and difficult to use. (And hterm could not show me tmux-powerline)

Version: 1.0.92
Platform: win32 10.0.18362
Plugins: none

**Comment by tuononh** [comment] 2019-11-04 09:11
Same here but it's only laggy when in fullscreen. Actually it's getting more lag when window is getting bigger.

**Comment by mkaraki** [comment] 2019-11-04 14:48
Thank you tunonh. I tried with small window and got better response (But it's still laggy).

**Comment by opensorceror** [comment] 2020-02-11 16:25
For me, the transparency and "Acrylic background" settings were causing it to be laggy. Once I turned off both, it's much snappier.

**Comment by Eugeny** [comment] 2020-07-27 14:15
Duplicate of #949

**Closed by Eugeny** 2020-07-27 14:15 UTC
