### ISSUE TITLE
No cursor in command window/shell list over lapping each other

### ISSUE THREAD

**Issue by ezr0** [Eugeny/terminus#2063] opened 2020-01-27 15:02 UTC
Version: 1.0.99
Platform: win32 10.0.18362
Plugins: none

When opening any shell window there is a blinking cursor but you cannot type anything.

Also when selecting the button next to the + button in the top title area displaying all the available shell's, a few of them are overlapping each other and showing as "undefined".

**Comment by Eugeny** [comment] 2020-01-28 17:24
Duplicate of #2052

**Closed** 2020-02-05 12:09 UTC
