### ISSUE TITLE
Opening a new tab doesn't work

### ISSUE THREAD

**Issue by zeralight** [Eugeny/terminus#1727] opened 2019-11-01 13:56 UTC
After clicking on the new tab button, nothing happens.
Devtools log:

> C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'LM' of undefined
TypeError: Cannot read property 'LM' of undefined
    at PowerShellCoreShellProvider.eval (powershellCore.ts:26)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js:65)
    at new ZoneAwarePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910)
    at __awaiter (tslib.es6.js:61)
    at PowerShellCoreShellProvider.provide (powershellCore.ts:21)
    at eval (terminal.service.ts:118)
    at Array.map (<anonymous>)
    at TerminalService.eval (terminal.service.ts:118)
    at Generator.next (<anonymous>)
    at resolvePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:831)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:741
    at rejected (tslib.es6.js:63)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:391)
    at Object.onInvoke (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17343)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:390)
    at Zone.run (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:150)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:889
    at ZoneDelegate.invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423)
    at Object.onInvokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334)

> C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getRegistryKey' of undefined
TypeError: Cannot read property 'getRegistryKey' of undefined
    at ShellIntegrationService.eval (shellIntegration.service.ts:49)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js:65)
    at new ZoneAwarePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910)
    at __awaiter (tslib.es6.js:61)
    at ShellIntegrationService.isInstalled (shellIntegration.service.ts:45)
    at ShellIntegrationService.eval (shellIntegration.service.ts:85)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js:65)
    at new ZoneAwarePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910)
    at resolvePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:831)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:741
    at rejected (tslib.es6.js:63)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:391)
    at Object.onInvoke (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17343)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:390)
    at Zone.run (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:150)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:889
    at ZoneDelegate.invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423)
    at Object.onInvokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334)

> C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getRegistryKey' of undefined
TypeError: Cannot read property 'getRegistryKey' of undefined
    at ShellIntegrationService.eval (shellIntegration.service.ts:49)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js:65)
    at new ZoneAwarePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910)
    at __awaiter (tslib.es6.js:61)
    at ShellIntegrationService.isInstalled (shellIntegration.service.ts:45)
    at SettingsTabComponent.eval (settingsTab.component.ts:90)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js:65)
    at new ZoneAwarePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910)
    at resolvePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:831)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:741
    at rejected (tslib.es6.js:63)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:391)
    at Object.onInvoke (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17343)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:390)
    at Zone.run (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:150)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:889
    at ZoneDelegate.invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423)
    at Object.onInvokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334)

- Windows 10 1903
- Version: 1.0.93-nightly.0

**Comment by williamJmelton** [comment] 2019-11-11 04:28
I am having this exact same error

**Comment by BHushanRathod** [comment] 2019-11-26 07:41
Getting the same error on Windows 10
Version: 1.0.94
Platform: win32 10.0.17763
Plugins: theme-hype

**Comment by Christilut** [comment] 2019-11-26 09:21
Same here, Windows 10
Version 1.0.94

Haven't changed any settings yet, just installed

**Comment by Eugeny** [comment] 2019-11-26 09:57
Duplicate of #1822

**Closed by Eugeny** 2019-11-26 09:57 UTC
Labels: S: Confirmed, T: Bug
