### ISSUE TITLE
[Support] Terminus add too many icons on the top bar of Gnome desktop 

### ISSUE THREAD

**Issue by TangdizhiH** [Eugeny/terminus#3663] opened 2021-04-03 21:56 UTC
**Environment:**
OS: Pos_os 20.10
Gnome version: 3.38.3
Terminus version: terminus-1.0.135-linux.deb

**Problem statement:**
I just downloaded and run this terminus using gdebi. The application works fine except that it adds a icon to the top bar everytime I use the "toggle terminal window". I'm using Terminus as a dropdown terminal solution on linux so this shortcut is quiet frequently used in my case. But its quiet unaesthetic to have repeated icon on the top bar, so I want to turn to you guys, asking what should I do to get rid of it.

Below is how my top bar looks like after using toggle shortcut three times, you can see three repeated terminus icon on the left part of the bar:
![图片](https://user-images.githubusercontent.com/45258158/113492628-0b1a0200-94d9-11eb-8fae-49ba776417ca.png)

**Step to reproduce:**
1. install terminus deb package using gdebi, and launch it.
2. using "toggle terminal window" shortcut.
3. a icon was added everytime the terminal window is toggled to disappear.

**Comment by Eugeny** [comment] 2021-04-04 17:54
Duplicate of #1642

**Closed by Eugeny** 2021-04-04 17:54 UTC
