### ISSUE TITLE
Double paste when using the mouse scroll button

### ISSUE THREAD

**Issue by fagnerpatricio** [Eugeny/terminus#1236] opened 2019-07-16 12:45 UTC
Hi

When I use the click of the mouse scroll button to paste a copied text it is performing the collage twice in a row.

![erroTerminus](https://user-images.githubusercontent.com/1405203/61295302-1b8ec400-a7ae-11e9-9488-6d3c04305cef.png)

Version: 1.0.79
Platform: linux 4.15.0-54-generic
Plugins: quick-cmds

**Comment by Eugeny** [comment] 2019-07-17 18:10
Duplicate of #945

**Closed by Eugeny** 2019-07-17 18:10 UTC
