### ISSUE TITLE
PPK doesn't work

### ISSUE THREAD

**Issue by cyquer** [Eugeny/terminus#3128] opened 2020-11-05 17:58 UTC
Version: 1.0.120
Platform: win32 10.0.19041
Plugins: none

Command failed: icacls C:\Users\XXXXX\AppData\Local\Temp\f-2020105-18320-1otg942.05vg /grant:r XXXXX-pc\XXXXX:(R,W)

SSH   X  Remote rejected opening a shell channel: TypeError: Cannot read property 'shell' of undefined

**Comment by Eugeny** [comment] 2021-05-15 16:53
Duplicate of #2018

**Closed by Eugeny** 2021-05-15 16:53 UTC
