### ISSUE TITLE
Sometimes it doesn't show any characters

### ISSUE THREAD

**Issue by zhufengning** [Eugeny/terminus#1001] opened 2019-06-03 14:36 UTC
It is just blank  
![img](https://i.loli.net/2019/06/03/5cf530419bebb18914.png)  
Version: 1.0.78
Platform: win32 10.0.17134
Plugins: none

**Comment by Eugeny** [comment] 2019-06-03 15:03
Duplicate of #729

**Closed by Eugeny** 2019-06-03 15:03 UTC
