### ISSUE TITLE
Unable to load new terminal window

### ISSUE THREAD

**Issue by Charles2295** [Eugeny/terminus#2012] opened 2020-01-16 09:51 UTC
Hello,
I have come across this a couple of times now with a few different Windows 10 installations. Opening a new terminal tab doesn't load and are unable to interact with the window at all. The only way to use Terminus is to use the 'quick connect' feature.

Thanks :)

Version: 1.0.99
Platform: win32 10.0.18362
Plugins: none

**Comment by Eugeny** [comment] 2020-01-16 09:53
Duplicate of #2011

**Closed by Eugeny** 2020-01-16 09:53 UTC
