### ISSUE TITLE
Tab move from windows

### ISSUE THREAD

**Issue by shenhfhep** [Eugeny/terminus#3694] opened 2021-04-13 05:47 UTC
Hi, I wonder if termius can move a tab from one windows to another window, I tried to move a tab to another window but failed. Is termuis has this function, if not will you add it in the future version ? thanks a lot !

**Comment by shenhfhep** [comment] 2021-04-13 07:00
Platform: windows 10

**Comment by Eugeny** [comment] 2021-04-16 18:21
Duplicate of #581

**Closed by Eugeny** 2021-04-16 18:21 UTC
