### ISSUE TITLE
Compact theme not showing properly

### ISSUE THREAD

**Issue by pvradu** [Eugeny/terminus#3202] opened 2020-12-13 19:32 UTC
Version: 1.0.122
Platform: win32 10.0.19042
Plugins: save-output, theme-windows10

Just upgraded to v1.0.122.

<img width="690" alt="Screenshot 2020-12-13 213112" src="https://user-images.githubusercontent.com/555644/102021734-933d9580-3d8a-11eb-971f-f4e3ab4e8f83.png">

**Comment by Eugeny** [comment] 2020-12-14 07:58
Duplicate of #3197

**Closed by Eugeny** 2020-12-14 07:58 UTC
