### ISSUE TITLE
Terminal doesn't respond to keyboard 

### ISSUE THREAD

**Issue by samliman** [Eugeny/terminus#3308] opened 2021-01-07 16:11 UTC
Version: 1.0.125
Platform: win32 10.0.18363
Plugins: none

After installing on Windows 10 or opening the portable version on windows 10, IT's strange because the terminal does accept input if I open to Git-Bash, but not cmd or powershell.

Thanks. 
![image](https://user-images.githubusercontent.com/36250079/103915507-892c5f80-50c8-11eb-8b80-d965cf2ebdbb.png)

**Comment by Eugeny** [comment] 2021-01-07 16:16
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by mscriv7** [comment] 2021-01-29 06:32
I am having the same problem - Terminus not accepting input for all terminal profiles including WSL (1) and CMD (stock).
This problem seems to have started from release 1.0.29 (or 1.0.28); the problem does not exists in 1.0.27.
I am also using portable on an older version of Windows 10 (Version 10.0.17763.1697)
I found that Terminus excepts input when ConPTY is enabled.

Below is the debugging console log when running CMD (stock) from Terminus 1.0.30:

Autofocus processing was blocked because a document already has a focused element.
C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-core\dist\index.js:5385 [terminal] Starting profile CMD (stock) {name: "CMD (stock)", shell: "cmd", icon: "<svg aria-hidden="true" focusable="false" data-pre…ss stroke="none" stroke-width="1px"></path></svg>", sessionOptions: {…}, isBuiltin: true}
C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-core\dist\index.js:5385 [terminal] Using session options: {command: "cmd.exe", args: Array(0), env: {…}, pauseAfterExit: undefined, cwd: ""}
/C:/Users/epamks/local/apps/terminus-1.0.30/resources/app.asar/dist/[object%20Module]:1 GET file:///C:/Users/epamks/local/apps/terminus-1.0.30/resources/app.asar/dist/[object%20Module] net::ERR_FILE_NOT_FOUND
C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:12931 Ignoring non-existent CWD: 
start @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:12931
addSession @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:13147
initializeSession @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:10090
(anonymous) @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:10085
SafeSubscriber.__tryOrUnsub @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205
SafeSubscriber.next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143
Subscriber._next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89
Subscriber.next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66
ThrowIfEmptySubscriber._next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\operators\throwIfEmpty.js:44
Subscriber.next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66
TakeSubscriber._next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\operators\take.js:54
Subscriber.next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66
Subject.next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subject.js:60
(anonymous) @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:8660
(anonymous) @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:3432
ZoneAwarePromise @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\zone.js\dist\zone.js:1335
__awaiter @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:3428
(anonymous) @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:8657
SafeSubscriber.__tryOrUnsub @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205
SafeSubscriber.next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143
Subscriber._next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89
Subscriber.next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66
ThrowIfEmptySubscriber._next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\operators\throwIfEmpty.js:44
Subscriber.next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66
TakeSubscriber._next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\operators\take.js:54
Subscriber.next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66
Subject.next @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subject.js:60
ReplaySubject.nextInfiniteTimeWindow @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\ReplaySubject.js:50
(anonymous) @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:11995
e.fire @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:69489
(anonymous) @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:69489
e.fire @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:69489
r.resize @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:69489
t.resize @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:69489
t.resize @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:69489
e.resize @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:69489
XTermFrontend.resizeHandler @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:12047
attach @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:12076
(anonymous) @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:8686
ZoneDelegate.invokeTask @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\zone.js\dist\zone.js:429
onInvokeTask @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:28303
ZoneDelegate.invokeTask @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\zone.js\dist\zone.js:428
Zone.runTask @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\zone.js\dist\zone.js:200
ZoneTask.invokeTask @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\zone.js\dist\zone.js:511
ZoneTask.invoke @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\zone.js\dist\zone.js:500
timer @ C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\zone.js\dist\zone.js:3059
processImmediate @ internal/timers.js:461
Show 17 more frames
4events.js:292 Uncaught Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:456)
    at WindowsTerminal._doWrite (C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\@terminus-term\node-pty\lib\windowsTerminal.js:114)
    at WindowsTerminal._defer (C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\@terminus-term\node-pty\lib\windowsTerminal.js:156)
    at WindowsTerminal._write (C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\@terminus-term\node-pty\lib\windowsTerminal.js:111)
    at WindowsTerminal.Terminal.write (C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\@terminus-term\node-pty\lib\terminal.js:81)
    at Session.write (C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:12988)
    at TerminalTabComponent.sendInput (C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:8736)
    at SafeSubscriber._next (C:\Users\epamks\local\apps\terminus-1.0.30\resources\builtin-plugins\terminus-terminal\dist\index.js:8964)
    at SafeSubscriber.__tryOrUnsub (C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205)
    at SafeSubscriber.next (C:\Users\epamks\local\apps\terminus-1.0.30\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143)

**Comment by Eugeny** [comment] 2021-02-13 14:04
Duplicate of #3397

**Closed by Eugeny** 2021-02-13 14:04 UTC
