### ISSUE TITLE
Version 1.0.125 - SSH issue

### ISSUE THREAD

**Issue by GanapathyRaman** [Eugeny/terminus#3296] opened 2021-01-05 04:05 UTC
Using version 1.0.125 bricks the terminus windows (turns into blank screen) while trying to SSH into a server from the saved SSH server list.

Note: SSH works fine when we type ssh command from the windows command prompt shell using Terminus. 
Issue exists only when we try to SSH using the saved list of servers.

**Comment by pzehner** [comment] 2021-01-06 07:56
I report the same problem on version 1.0.123 on MS Windows 10 1809.

On some SSH connections, the Terminus window goes completely empty. When I reopen Terminus, it tries to reestablish the connection and the window goes empty again. I do not have time to access debug tools.

**Comment by supermanc88** [comment] 2021-01-06 09:42
I found the same problem when connect 10.20.88.225.
but connect 10.20.88.224 is ok.

**Comment by JamesGaither** [comment] 2021-01-07 03:33
Same issue as above. Using terminus 1.0.123 & 1.0.125 on MS Windows I find some SSH connections (to a RH6.6 server specifically) causes the terminus window to go completely empty. Other servers (such as ubuntu18.04) ssh does not cause the issue. Terminus 1.0.122 does not have this issue.

**Comment by SergioSuarezDev** [comment] 2021-01-07 12:32
Same on MacOS 1.0.125

**Comment by Eugeny** [comment] 2021-01-09 16:02
Can you give this Windows build a test please? (downloads below) https://github.com/Eugeny/terminus/actions/runs/474206755

**Comment by supermanc88** [comment] 2021-01-11 02:24
https://user-images.githubusercontent.com/8957358/104142536-015f9180-53f7-11eb-8c1b-85f54a724ea2.mp4

The problem still exists

> Can you give this Windows build a test please? (downloads below) https://github.com/Eugeny/terminus/actions/runs/474206755
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Eugeny/terminus](https://github.com/Eugeny/terminus)**A terminal for a more modern age. Contribute to Eugeny/terminus development by creating an account on GitHub.

**Comment by GanapathyRaman** [comment] 2021-01-11 06:06
No not working. The SSH problem still exists.

> Can you give this Windows build a test please? (downloads below) https://github.com/Eugeny/terminus/actions/runs/474206755
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Eugeny/terminus](https://github.com/Eugeny/terminus)**A terminal for a more modern age. Contribute to Eugeny/terminus development by creating an account on GitHub.

**Comment by supermanc88** [comment] 2021-01-11 06:34
target env:
# cat /etc/redhat-release 
CentOS release 6.10 (Final)

openssh version:
OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013

if update openssh-server to OpenSSH_7.6p1, the problem is solved.

I hope this information is helpful to you

**Comment by Mirulmaar** [comment] 2021-01-11 08:57
Same problem with OpenSSH_5.3p1, OpenSSL 1.0.1e-fips. 
For OpenSSH_7.4p1, OpenSSL 1.0.2k-fips no problems.

**Comment by Eugeny** [comment] 2021-01-11 11:00
Thanks. This is a native crash in Node during DH key exchange. That's why it doesn't crash when the server negotiates an ECDH kex. I'm trying to figure out how to work around this.

**Comment by Eugeny** [comment] 2021-01-12 17:32
Here's another build to try: https://github.com/Eugeny/terminus/actions/runs/480758253

I've decided to roll back Electron until the issues are fixed upstream.

**Comment by supermanc88** [comment] 2021-01-13 02:21
![1610503873](https://user-images.githubusercontent.com/8957358/104397801-7c0be680-5588-11eb-9633-e8b5026ad19d.jpg)
The crash problem was resolved, but one of the algorithms was not supported

> Here's another build to try: https://github.com/Eugeny/terminus/actions/runs/480758253
> 
> I've decided to roll back Electron until the issues are fixed upstream.
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Eugeny/terminus](https://github.com/Eugeny/terminus)**A terminal for a more modern age. Contribute to Eugeny/terminus development by creating an account on GitHub.

**Comment by GanapathyRaman** [comment] 2021-01-13 04:35
I am able to SSH into my servers using this nightly build. Thanks

> Here's another build to try: https://github.com/Eugeny/terminus/actions/runs/480758253
> 
> I've decided to roll back Electron until the issues are fixed upstream.
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Eugeny/terminus](https://github.com/Eugeny/terminus)**A terminal for a more modern age. Contribute to Eugeny/terminus development by creating an account on GitHub.

**Comment by Mirulmaar** [comment] 2021-01-13 07:07
> Here's another build to try: https://github.com/Eugeny/terminus/actions/runs/480758253
> 
> I've decided to roll back Electron until the issues are fixed upstream.
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Eugeny/terminus](https://github.com/Eugeny/terminus)**A terminal for a more modern age. Contribute to Eugeny/terminus development by creating an account on GitHub.

Thanks, it works!

**Comment by Eugeny** [comment] 2021-01-13 18:08
This should now be fixed in Alpha 127. Let me know if you still experience problems and I'll reopen.

**Closed by Eugeny** 2021-01-13 18:08 UTC
