### ISSUE TITLE
SSH connection issue after update.

### ISSUE THREAD

**Issue by dsx12** [Eugeny/terminus#1182] opened 2019-07-04 17:14 UTC
After updating terminus won't connect to my vps it just hangs.
output:

Connecting to 127.0.0.1
Loading private key from C:\Users\admin/.ssh/id_rsa......................................................................................................................................

**Comment by Legendbender** [comment] 2019-07-04 18:14
Same in here

**Comment by luiszimmermann** [comment] 2019-07-04 19:27
same here

**Comment by luiszimmermann** [comment] 2019-07-04 20:01
```
entry.preload.ts:37 

TypeError: r.callback is not a function
    at C:\Users\luisz\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@terminus-term\windows-process-tree\lib\index.js:74
    at Array.forEach (<anonymous>)
    at C:\Users\luisz\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@terminus-term\windows-process-tree\lib\index.js:73
```

**Comment by R3n0x** [comment] 2019-07-04 20:42
Same here too.

**Comment by ryuzheng** [comment] 2019-07-05 03:13
Same here too, and can I close the auto update?

**Comment by Eugeny** [comment] 2019-07-05 13:11
Duplicate of #1161

**Comment by Eugeny** [comment] 2019-07-05 13:11
Please download the updated A85 build here: https://github.com/Eugeny/terminus/releases/tag/v1.0.85

**Closed by Eugeny** 2019-07-05 13:11 UTC
