### ISSUE TITLE
Background transparency

### ISSUE THREAD

**Issue by py-alpha-wolf** [Eugeny/terminus#3490] opened 2021-02-22 08:37 UTC
Hey, I am on my LinuxPC ( Ubuntu ) not possible to use the "blur" for the background. The opacity slider has no effect no matter how I move it. How can I change this?

**Comment by Mohammed-Taher** [comment] 2021-03-11 08:31
I have the same problem. The opacity slider has no effect on linux.

**Comment by Eugeny** [comment] 2021-03-13 18:54
Duplicate of #832

**Closed by Eugeny** 2021-03-13 18:54 UTC

**Comment by TheAalCh3m1st** [comment] 2024-11-04 01:01
This is still an issue in Nov/2024.

**Comment by Eugeny** [comment] 2024-11-04 08:19
I know what date it is today, why don't you consider helping solve the issue instead?

**Comment by TheAalCh3m1st** [comment] 2024-11-06 01:34
Chief, I didn't 'mean to be rude I was just letting the community know the issue still exist today. I'm new to helping on community projects and would love to contribute in any fashion that I can. My apologies!

**Comment by boutmos** [comment] 2024-11-18 06:07
Same on Linux Mint 22
