### ISSUE TITLE
Malayalam Language support  Issue

### ISSUE THREAD

**Issue by mujeebcpy** [Eugeny/terminus#87] opened 2017-07-06 03:36 UTC
The language Malayalam (ml) is not working fine in Terminal. ്+zwj  is not recognizing. 

![image](https://user-images.githubusercontent.com/24728052/27894533-521aed80-622a-11e7-8e30-b3dcc7870e33.png)

**Comment by Eugeny** [comment] 2017-07-08 11:46
Should be fixed in the latest Alpha, please confirm

**Comment by Eugeny** [comment] 2018-02-12 16:22
Closing due to the lack of activity. Please feel free to reopen if the issue is still relevant!

**Closed by Eugeny** 2018-02-12 16:22 UTC
Labels: S: Incomplete, T: Bug
