### ISSUE TITLE
Is terminus supporting mouse events?

### ISSUE THREAD

**Issue by melveg** [Eugeny/terminus#96] opened 2017-07-06 13:29 UTC
I am using windows 10 with bash on windows.. I am using tabs and tmux with terminus ... Thats cool and all But.. when i try to add mouse mode to tmux in terminus... the terminal is not listening the click for selecting the pane.. My version of windows is creators update... in the native bash on windows tmux with mouse events works just fine.

**Comment by Calinou** [comment] 2017-07-06 13:47
This issue is probably a duplicate of https://github.com/Eugeny/terminus/issues/22.

**Comment by Eugeny** [comment] 2017-07-08 11:38
Yes, mouse support in Bash on Windows is currently broken (#22)

**Closed by Eugeny** 2017-07-08 11:38 UTC

**Comment by nickjj** [comment] 2018-12-08 12:02
Has there been any progress with this?

This is still busted with Windows 18.09.
