### ISSUE TITLE
Settings button sometimes doesn't do anything?

### ISSUE THREAD

**Issue by cburj** [Eugeny/terminus#1628] opened 2019-10-15 07:27 UTC
Version: 1.0.92
Platform: win32 10.0.18362
Plugins: none

Quite regularly, the settings icon does not open the settings menu. Even the one on the splash screen fails to open the settings screen. Loving Terminus by the way!

**Comment by Eugeny** [comment] 2019-10-16 19:53
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by x1nas** [comment] 2019-10-17 08:18
Same problem on Linux

Error from Developers Tools

> errors.ts:35 ERROR YAMLException {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d…27:9)↵    at dump (webpack-internal:///266:817:7)"}mark: undefinedmessage: "unacceptable kind of an object to dump [object Undefined]"name: "YAMLException"reason: "unacceptable kind of an object to dump [object Undefined]"stack: "YAMLException: unacceptable kind of an object to dump [object Undefined]↵    at writeNode (webpack-internal:///266:756:13)↵    at writeBlockMapping (webpack-internal:///266:634:10)↵    at writeNode (webpack-internal:///266:727:9)↵    at writeBlockSequence (webpack-internal:///266:521:9)↵    at writeNode (webpack-internal:///266:740:9)↵    at writeBlockMapping (webpack-internal:///266:634:10)↵    at writeNode (webpack-internal:///266:727:9)↵    at writeBlockMapping (webpack-internal:///266:634:10)↵    at writeNode (webpack-internal:///266:727:9)↵    at dump (webpack-internal:///266:817:7)"__proto__: Error
> defaultErrorLogger @ errors.ts:35
> ErrorHandler.handleError @ error_handler.ts:51
> dispatchEvent @ util.ts:137
> (anonymous) @ element.ts:200
> (anonymous) @ dom_renderer.ts:52
> ZoneDelegate.invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:423
> onInvokeTask @ ng_zone.ts:262
> ZoneDelegate.invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:422
> Zone.runTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:195
> ZoneTask.invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:498
> invokeTask @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:1744
> globalZoneAwareCallback @ /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:1770

**Comment by cburj** [comment] 2019-10-23 08:06
Seems to have fixed itself after a quick re-install. 😁

**Comment by Eugeny** [comment] 2019-11-06 11:48
Duplicate of #1665

**Closed by Eugeny** 2019-11-06 11:48 UTC
