### ISSUE TITLE
failed to start a ssh connection in a connected SSH

### ISSUE THREAD

**Issue by ZehuanZhang** [Eugeny/terminus#2887] opened 2020-08-11 07:30 UTC
When I use terminus to start SSH connection with server A and trying to start a connection through A with B, the ssh command has no any response.

![image](https://user-images.githubusercontent.com/20352723/89869086-70398400-dbe6-11ea-925a-601f511147c9.png)

There are two machines A and B, A is a master server for manage server B.
This bug only occurs in Terminus SSH and not in MINGW64 or CMD (also opened in Terminus).

**Comment by marcinbojko** [comment] 2020-08-11 10:08
I've tested all releases, and it started since 1.0.115. Had to go back to 1.0.14

**Comment by zhuli19901106** [comment] 2020-08-12 05:53
Exactly, just found out by reverting to an older version.

This should be a newly introduced bug from the most recent updates.

**Comment by urbels** [comment] 2020-08-12 07:33
Same problem on w10. Reverting back to 1.114 helps.

**Comment by ZehuanZhang** [comment] 2020-08-12 07:40
Thanks, guys.
I've reverted to version 1.0.114, hope this bug could be solved as soon as possible.

**Comment by gabriellovate** [comment] 2020-08-12 15:12
Same issue here, will revert to 1.0.114

**Comment by Eugeny** [comment] 2020-08-12 19:32
Duplicate of #2868

**Closed by Eugeny** 2020-08-12 19:32 UTC
